# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapped.ui'
#
# Created: Mon May 20 14:25:20 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(762, 574)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.mapTab = QtGui.QWidget()
        self.mapTab.setObjectName(_fromUtf8("mapTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.mapTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.map = QtGui.QGraphicsView(self.mapTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map.sizePolicy().hasHeightForWidth())
        self.map.setSizePolicy(sizePolicy)
        self.map.setObjectName(_fromUtf8("map"))
        self.gridLayout_2.addWidget(self.map, 0, 0, 1, 1)
        self.palette = QtGui.QGraphicsView(self.mapTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.palette.sizePolicy().hasHeightForWidth())
        self.palette.setSizePolicy(sizePolicy)
        self.palette.setMinimumSize(QtCore.QSize(160, 0))
        self.palette.setMaximumSize(QtCore.QSize(200, 16777215))
        self.palette.setObjectName(_fromUtf8("palette"))
        self.gridLayout_2.addWidget(self.palette, 0, 1, 1, 1)
        self.tabWidget.addTab(self.mapTab, _fromUtf8(""))
        self.movPermissionsTab = QtGui.QWidget()
        self.movPermissionsTab.setObjectName(_fromUtf8("movPermissionsTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.movPermissionsTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.movPermissionsMap = QtGui.QGraphicsView(self.movPermissionsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movPermissionsMap.sizePolicy().hasHeightForWidth())
        self.movPermissionsMap.setSizePolicy(sizePolicy)
        self.movPermissionsMap.setObjectName(_fromUtf8("movPermissionsMap"))
        self.gridLayout_3.addWidget(self.movPermissionsMap, 0, 0, 1, 1)
        self.MovPermissionsPalette = QtGui.QGraphicsView(self.movPermissionsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MovPermissionsPalette.sizePolicy().hasHeightForWidth())
        self.MovPermissionsPalette.setSizePolicy(sizePolicy)
        self.MovPermissionsPalette.setMinimumSize(QtCore.QSize(160, 0))
        self.MovPermissionsPalette.setMaximumSize(QtCore.QSize(200, 16777215))
        self.MovPermissionsPalette.setObjectName(_fromUtf8("MovPermissionsPalette"))
        self.gridLayout_3.addWidget(self.MovPermissionsPalette, 0, 1, 1, 1)
        self.tabWidget.addTab(self.movPermissionsTab, _fromUtf8(""))
        self.EventsTab = QtGui.QWidget()
        self.EventsTab.setObjectName(_fromUtf8("EventsTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.EventsTab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.map_2 = QtGui.QGraphicsView(self.EventsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_2.sizePolicy().hasHeightForWidth())
        self.map_2.setSizePolicy(sizePolicy)
        self.map_2.setObjectName(_fromUtf8("map_2"))
        self.gridLayout_4.addWidget(self.map_2, 0, 0, 1, 1)
        self.EventsBox = QtGui.QGroupBox(self.EventsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EventsBox.sizePolicy().hasHeightForWidth())
        self.EventsBox.setSizePolicy(sizePolicy)
        self.EventsBox.setObjectName(_fromUtf8("EventsBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.EventsBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.EventsBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.EventsBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 5, 2, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.EventsBox)
        self.pushButton_2.setMaximumSize(QtCore.QSize(27, 16777215))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_5.addWidget(self.pushButton_2, 2, 4, 1, 1)
        self.pushButton = QtGui.QPushButton(self.EventsBox)
        self.pushButton.setMaximumSize(QtCore.QSize(27, 16777215))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_5.addWidget(self.pushButton, 0, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.EventsBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 2, 2, 1, 1)
        self.label = QtGui.QLabel(self.EventsBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 0, 1, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.EventsBox)
        self.pushButton_4.setMaximumSize(QtCore.QSize(27, 16777215))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_5.addWidget(self.pushButton_4, 4, 4, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.EventsBox)
        self.pushButton_3.setMaximumSize(QtCore.QSize(27, 16777215))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_5.addWidget(self.pushButton_3, 5, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.EventsBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 4, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.EventsBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 5, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.EventsBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.EventsBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 4, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 7, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.EventsBox)
        self.groupBox.setEnabled(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5.addWidget(self.groupBox, 6, 1, 1, 1)
        self.gridLayout_4.addWidget(self.EventsBox, 0, 1, 1, 1)
        self.tabWidget.addTab(self.EventsTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 762, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setMinimumSize(QtCore.QSize(180, 129))
        self.dockWidget.setBaseSize(QtCore.QSize(0, 0))
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.treeView = QtGui.QTreeView(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMinimumSize(QtCore.QSize(50, 0))
        self.treeView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeView.setIndentation(10)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.verticalLayout.addWidget(self.treeView)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actionLoad_ROM = QtGui.QAction(MainWindow)
        self.actionLoad_ROM.setObjectName(_fromUtf8("actionLoad_ROM"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.menuFile.addAction(self.actionLoad_ROM)
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Blue Spider", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mapTab), _translate("MainWindow", "Map", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.movPermissionsTab), _translate("MainWindow", "Movement Permissions", None))
        self.EventsBox.setTitle(_translate("MainWindow", "Add events", None))
        self.label_4.setText(_translate("MainWindow", "People:", None))
        self.label_8.setText(_translate("MainWindow", "0", None))
        self.pushButton_2.setText(_translate("MainWindow", "+", None))
        self.pushButton.setText(_translate("MainWindow", "+", None))
        self.label_3.setText(_translate("MainWindow", "0", None))
        self.label.setText(_translate("MainWindow", "Warps: ", None))
        self.pushButton_4.setText(_translate("MainWindow", "+", None))
        self.pushButton_3.setText(_translate("MainWindow", "+", None))
        self.label_6.setText(_translate("MainWindow", "0", None))
        self.label_7.setText(_translate("MainWindow", "Signposts:", None))
        self.label_2.setText(_translate("MainWindow", "0", None))
        self.label_5.setText(_translate("MainWindow", "Triggers:", None))
        self.groupBox.setTitle(_translate("MainWindow", "Edit event", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.EventsTab), _translate("MainWindow", "Events", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionLoad_ROM.setText(_translate("MainWindow", "Load ROM", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))

