# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapped.ui'
#
# Created: Thu Jan 29 23:09:52 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(988, 706)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.treeView = QtGui.QTreeView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMinimumSize(QtCore.QSize(50, 0))
        self.treeView.setMaximumSize(QtCore.QSize(170, 16777215))
        self.treeView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeView.setIndentation(10)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.gridLayout.addWidget(self.treeView, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.mapTab = QtGui.QWidget()
        self.mapTab.setObjectName(_fromUtf8("mapTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.mapTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.map = QtGui.QGraphicsView(self.mapTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map.sizePolicy().hasHeightForWidth())
        self.map.setSizePolicy(sizePolicy)
        self.map.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.map.setObjectName(_fromUtf8("map"))
        self.gridLayout_2.addWidget(self.map, 0, 0, 1, 1)
        self.palette = QtGui.QGraphicsView(self.mapTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.palette.sizePolicy().hasHeightForWidth())
        self.palette.setSizePolicy(sizePolicy)
        self.palette.setMinimumSize(QtCore.QSize(160, 0))
        self.palette.setMaximumSize(QtCore.QSize(200, 16777215))
        self.palette.setObjectName(_fromUtf8("palette"))
        self.gridLayout_2.addWidget(self.palette, 0, 1, 1, 1)
        self.tabWidget.addTab(self.mapTab, _fromUtf8(""))
        self.movPermissionsTab = QtGui.QWidget()
        self.movPermissionsTab.setObjectName(_fromUtf8("movPermissionsTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.movPermissionsTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.movPermissionsMap = QtGui.QGraphicsView(self.movPermissionsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movPermissionsMap.sizePolicy().hasHeightForWidth())
        self.movPermissionsMap.setSizePolicy(sizePolicy)
        self.movPermissionsMap.setObjectName(_fromUtf8("movPermissionsMap"))
        self.gridLayout_3.addWidget(self.movPermissionsMap, 0, 0, 1, 1)
        self.MovPermissionsPalette = QtGui.QGraphicsView(self.movPermissionsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MovPermissionsPalette.sizePolicy().hasHeightForWidth())
        self.MovPermissionsPalette.setSizePolicy(sizePolicy)
        self.MovPermissionsPalette.setMinimumSize(QtCore.QSize(160, 0))
        self.MovPermissionsPalette.setMaximumSize(QtCore.QSize(200, 16777215))
        self.MovPermissionsPalette.setObjectName(_fromUtf8("MovPermissionsPalette"))
        self.gridLayout_3.addWidget(self.MovPermissionsPalette, 0, 1, 1, 1)
        self.tabWidget.addTab(self.movPermissionsTab, _fromUtf8(""))
        self.eventsTab = QtGui.QWidget()
        self.eventsTab.setObjectName(_fromUtf8("eventsTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.eventsTab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.eventMap = QtGui.QGraphicsView(self.eventsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventMap.sizePolicy().hasHeightForWidth())
        self.eventMap.setSizePolicy(sizePolicy)
        self.eventMap.setObjectName(_fromUtf8("eventMap"))
        self.gridLayout_4.addWidget(self.eventMap, 0, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.eventsTab)
        self.scrollArea.setMinimumSize(QtCore.QSize(270, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(280, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 372, 721))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.EventsBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EventsBox.sizePolicy().hasHeightForWidth())
        self.EventsBox.setSizePolicy(sizePolicy)
        self.EventsBox.setObjectName(_fromUtf8("EventsBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.EventsBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_4 = QtGui.QLabel(self.EventsBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 2, 1, 1, 1)
        self.addTriggerButton = QtGui.QPushButton(self.EventsBox)
        self.addTriggerButton.setEnabled(True)
        self.addTriggerButton.setMaximumSize(QtCore.QSize(27, 16777215))
        self.addTriggerButton.setObjectName(_fromUtf8("addTriggerButton"))
        self.gridLayout_5.addWidget(self.addTriggerButton, 4, 5, 1, 1)
        self.num_of_signposts = QtGui.QLabel(self.EventsBox)
        self.num_of_signposts.setObjectName(_fromUtf8("num_of_signposts"))
        self.gridLayout_5.addWidget(self.num_of_signposts, 5, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.EventsBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 4, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.EventsBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 0, 1, 1, 1)
        self.num_of_warps = QtGui.QLabel(self.EventsBox)
        self.num_of_warps.setObjectName(_fromUtf8("num_of_warps"))
        self.gridLayout_5.addWidget(self.num_of_warps, 0, 2, 1, 1)
        self.num_of_people = QtGui.QLabel(self.EventsBox)
        self.num_of_people.setObjectName(_fromUtf8("num_of_people"))
        self.gridLayout_5.addWidget(self.num_of_people, 2, 2, 1, 1)
        self.num_of_triggers = QtGui.QLabel(self.EventsBox)
        self.num_of_triggers.setObjectName(_fromUtf8("num_of_triggers"))
        self.gridLayout_5.addWidget(self.num_of_triggers, 4, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.EventsBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 5, 1, 1, 1)
        self.addSignpostButton = QtGui.QPushButton(self.EventsBox)
        self.addSignpostButton.setEnabled(True)
        self.addSignpostButton.setMaximumSize(QtCore.QSize(27, 16777215))
        self.addSignpostButton.setObjectName(_fromUtf8("addSignpostButton"))
        self.gridLayout_5.addWidget(self.addSignpostButton, 5, 5, 1, 1)
        self.addPersonButton = QtGui.QPushButton(self.EventsBox)
        self.addPersonButton.setEnabled(True)
        self.addPersonButton.setMaximumSize(QtCore.QSize(27, 16777215))
        self.addPersonButton.setObjectName(_fromUtf8("addPersonButton"))
        self.gridLayout_5.addWidget(self.addPersonButton, 2, 5, 1, 1)
        self.remWarpButton = QtGui.QPushButton(self.EventsBox)
        self.remWarpButton.setEnabled(True)
        self.remWarpButton.setMaximumSize(QtCore.QSize(27, 16777215))
        self.remWarpButton.setObjectName(_fromUtf8("remWarpButton"))
        self.gridLayout_5.addWidget(self.remWarpButton, 0, 4, 1, 1)
        self.addWarpButton = QtGui.QPushButton(self.EventsBox)
        self.addWarpButton.setEnabled(True)
        self.addWarpButton.setMaximumSize(QtCore.QSize(27, 16777215))
        self.addWarpButton.setObjectName(_fromUtf8("addWarpButton"))
        self.gridLayout_5.addWidget(self.addWarpButton, 0, 5, 1, 1)
        self.remPersonButton = QtGui.QPushButton(self.EventsBox)
        self.remPersonButton.setEnabled(True)
        self.remPersonButton.setMaximumSize(QtCore.QSize(27, 16777215))
        self.remPersonButton.setObjectName(_fromUtf8("remPersonButton"))
        self.gridLayout_5.addWidget(self.remPersonButton, 2, 4, 1, 1)
        self.remTriggerButton = QtGui.QPushButton(self.EventsBox)
        self.remTriggerButton.setEnabled(True)
        self.remTriggerButton.setMaximumSize(QtCore.QSize(27, 16777215))
        self.remTriggerButton.setObjectName(_fromUtf8("remTriggerButton"))
        self.gridLayout_5.addWidget(self.remTriggerButton, 4, 4, 1, 1)
        self.remSignpostButton = QtGui.QPushButton(self.EventsBox)
        self.remSignpostButton.setEnabled(True)
        self.remSignpostButton.setMaximumSize(QtCore.QSize(27, 16777215))
        self.remSignpostButton.setObjectName(_fromUtf8("remSignpostButton"))
        self.gridLayout_5.addWidget(self.remSignpostButton, 5, 4, 1, 1)
        self.verticalLayout_2.addWidget(self.EventsBox)
        self.eventsStackedWidget = QtGui.QStackedWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventsStackedWidget.sizePolicy().hasHeightForWidth())
        self.eventsStackedWidget.setSizePolicy(sizePolicy)
        self.eventsStackedWidget.setObjectName(_fromUtf8("eventsStackedWidget"))
        self.emptyEditor = QtGui.QWidget()
        self.emptyEditor.setObjectName(_fromUtf8("emptyEditor"))
        self.eventsStackedWidget.addWidget(self.emptyEditor)
        self.warpEditor = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warpEditor.sizePolicy().hasHeightForWidth())
        self.warpEditor.setSizePolicy(sizePolicy)
        self.warpEditor.setObjectName(_fromUtf8("warpEditor"))
        self.formLayout_2 = QtGui.QFormLayout(self.warpEditor)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_10 = QtGui.QLabel(self.warpEditor)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self._8 = QtGui.QHBoxLayout()
        self._8.setObjectName(_fromUtf8("_8"))
        self.w_x = QtGui.QLineEdit(self.warpEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_x.sizePolicy().hasHeightForWidth())
        self.w_x.setSizePolicy(sizePolicy)
        self.w_x.setMaximumSize(QtCore.QSize(40, 16777215))
        self.w_x.setObjectName(_fromUtf8("w_x"))
        self._8.addWidget(self.w_x)
        self.w_y = QtGui.QLineEdit(self.warpEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_y.sizePolicy().hasHeightForWidth())
        self.w_y.setSizePolicy(sizePolicy)
        self.w_y.setMaximumSize(QtCore.QSize(40, 16777215))
        self.w_y.setObjectName(_fromUtf8("w_y"))
        self._8.addWidget(self.w_y)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.FieldRole, self._8)
        self.label_11 = QtGui.QLabel(self.warpEditor)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.w_unknown1 = QtGui.QLineEdit(self.warpEditor)
        self.w_unknown1.setObjectName(_fromUtf8("w_unknown1"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.w_unknown1)
        self.label_12 = QtGui.QLabel(self.warpEditor)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_12)
        self.w_bank_n = QtGui.QLineEdit(self.warpEditor)
        self.w_bank_n.setObjectName(_fromUtf8("w_bank_n"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.w_bank_n)
        self.label_13 = QtGui.QLabel(self.warpEditor)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_13)
        self.w_map_n = QtGui.QLineEdit(self.warpEditor)
        self.w_map_n.setObjectName(_fromUtf8("w_map_n"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.w_map_n)
        self.label_14 = QtGui.QLabel(self.warpEditor)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_14)
        self.w_warp_n = QtGui.QLineEdit(self.warpEditor)
        self.w_warp_n.setObjectName(_fromUtf8("w_warp_n"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.w_warp_n)
        self.warpGoToMapButton = QtGui.QPushButton(self.warpEditor)
        self.warpGoToMapButton.setObjectName(_fromUtf8("warpGoToMapButton"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.warpGoToMapButton)
        self.openInEmulatorButton = QtGui.QPushButton(self.warpEditor)
        self.openInEmulatorButton.setEnabled(False)
        self.openInEmulatorButton.setObjectName(_fromUtf8("openInEmulatorButton"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.openInEmulatorButton)
        self.eventsStackedWidget.addWidget(self.warpEditor)
        self.personEditor = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.personEditor.sizePolicy().hasHeightForWidth())
        self.personEditor.setSizePolicy(sizePolicy)
        self.personEditor.setObjectName(_fromUtf8("personEditor"))
        self.formLayout = QtGui.QFormLayout(self.personEditor)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_16 = QtGui.QLabel(self.personEditor)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_16)
        self.person_num = QtGui.QLineEdit(self.personEditor)
        self.person_num.setInputMask(_fromUtf8(""))
        self.person_num.setObjectName(_fromUtf8("person_num"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.person_num)
        self.label_17 = QtGui.QLabel(self.personEditor)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtGui.QLabel(self.personEditor)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_18)
        self._3 = QtGui.QHBoxLayout()
        self._3.setObjectName(_fromUtf8("_3"))
        self.p_unknown1 = QtGui.QLineEdit(self.personEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_unknown1.sizePolicy().hasHeightForWidth())
        self.p_unknown1.setSizePolicy(sizePolicy)
        self.p_unknown1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.p_unknown1.setObjectName(_fromUtf8("p_unknown1"))
        self._3.addWidget(self.p_unknown1)
        self.p_unknown2 = QtGui.QLineEdit(self.personEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_unknown2.sizePolicy().hasHeightForWidth())
        self.p_unknown2.setSizePolicy(sizePolicy)
        self.p_unknown2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.p_unknown2.setObjectName(_fromUtf8("p_unknown2"))
        self._3.addWidget(self.p_unknown2)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self._3)
        self.label_15 = QtGui.QLabel(self.personEditor)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_15)
        self._2 = QtGui.QHBoxLayout()
        self._2.setObjectName(_fromUtf8("_2"))
        self.p_x = QtGui.QLineEdit(self.personEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_x.sizePolicy().hasHeightForWidth())
        self.p_x.setSizePolicy(sizePolicy)
        self.p_x.setMaximumSize(QtCore.QSize(40, 16777215))
        self.p_x.setObjectName(_fromUtf8("p_x"))
        self._2.addWidget(self.p_x)
        self.p_y = QtGui.QLineEdit(self.personEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_y.sizePolicy().hasHeightForWidth())
        self.p_y.setSizePolicy(sizePolicy)
        self.p_y.setMaximumSize(QtCore.QSize(40, 16777215))
        self.p_y.setObjectName(_fromUtf8("p_y"))
        self._2.addWidget(self.p_y)
        self.formLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self._2)
        self.label_19 = QtGui.QLabel(self.personEditor)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_19)
        self.p_unknown3 = QtGui.QLineEdit(self.personEditor)
        self.p_unknown3.setObjectName(_fromUtf8("p_unknown3"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.p_unknown3)
        self.label_20 = QtGui.QLabel(self.personEditor)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_20)
        self.p_mov_type = QtGui.QComboBox(self.personEditor)
        self.p_mov_type.setObjectName(_fromUtf8("p_mov_type"))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.p_mov_type.addItem(_fromUtf8(""))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.p_mov_type)
        self.label_21 = QtGui.QLabel(self.personEditor)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_21)
        self.p_mov = QtGui.QLineEdit(self.personEditor)
        self.p_mov.setObjectName(_fromUtf8("p_mov"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.p_mov)
        self.label_22 = QtGui.QLabel(self.personEditor)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_22)
        self.p_unknown4 = QtGui.QLineEdit(self.personEditor)
        self.p_unknown4.setObjectName(_fromUtf8("p_unknown4"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.p_unknown4)
        self.label_23 = QtGui.QLabel(self.personEditor)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_23)
        self.label_24 = QtGui.QLabel(self.personEditor)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_24)
        self.label_25 = QtGui.QLabel(self.personEditor)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.label_25)
        self.label_26 = QtGui.QLabel(self.personEditor)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.LabelRole, self.label_26)
        self.label_27 = QtGui.QLabel(self.personEditor)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.formLayout.setWidget(16, QtGui.QFormLayout.LabelRole, self.label_27)
        self.p_flag = QtGui.QLineEdit(self.personEditor)
        self.p_flag.setObjectName(_fromUtf8("p_flag"))
        self.formLayout.setWidget(16, QtGui.QFormLayout.FieldRole, self.p_flag)
        self.label_28 = QtGui.QLabel(self.personEditor)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout.setWidget(17, QtGui.QFormLayout.LabelRole, self.label_28)
        self._6 = QtGui.QHBoxLayout()
        self._6.setObjectName(_fromUtf8("_6"))
        self.p_unknown6 = QtGui.QLineEdit(self.personEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_unknown6.sizePolicy().hasHeightForWidth())
        self.p_unknown6.setSizePolicy(sizePolicy)
        self.p_unknown6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.p_unknown6.setObjectName(_fromUtf8("p_unknown6"))
        self._6.addWidget(self.p_unknown6)
        self.p_unknown7 = QtGui.QLineEdit(self.personEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_unknown7.sizePolicy().hasHeightForWidth())
        self.p_unknown7.setSizePolicy(sizePolicy)
        self.p_unknown7.setMaximumSize(QtCore.QSize(40, 16777215))
        self.p_unknown7.setObjectName(_fromUtf8("p_unknown7"))
        self._6.addWidget(self.p_unknown7)
        self.formLayout.setLayout(17, QtGui.QFormLayout.FieldRole, self._6)
        self.p_script_offset = QtGui.QLineEdit(self.personEditor)
        self.p_script_offset.setObjectName(_fromUtf8("p_script_offset"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.FieldRole, self.p_script_offset)
        self.p_view_radius = QtGui.QLineEdit(self.personEditor)
        self.p_view_radius.setObjectName(_fromUtf8("p_view_radius"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.p_view_radius)
        self.p_unknown5 = QtGui.QLineEdit(self.personEditor)
        self.p_unknown5.setObjectName(_fromUtf8("p_unknown5"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.p_unknown5)
        self.p_edit_script = QtGui.QPushButton(self.personEditor)
        self.p_edit_script.setObjectName(_fromUtf8("p_edit_script"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.FieldRole, self.p_edit_script)
        self.spriteImg = QtGui.QGraphicsView(self.personEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spriteImg.sizePolicy().hasHeightForWidth())
        self.spriteImg.setSizePolicy(sizePolicy)
        self.spriteImg.setMinimumSize(QtCore.QSize(16, 32))
        self.spriteImg.setMaximumSize(QtCore.QSize(16, 32))
        self.spriteImg.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.spriteImg.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.spriteImg.setObjectName(_fromUtf8("spriteImg"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spriteImg)
        self.label_9 = QtGui.QLabel(self.personEditor)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.sprite_num = QtGui.QSpinBox(self.personEditor)
        self.sprite_num.setPrefix(_fromUtf8(""))
        self.sprite_num.setObjectName(_fromUtf8("sprite_num"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.sprite_num)
        self.is_a_trainer = QtGui.QLineEdit(self.personEditor)
        self.is_a_trainer.setObjectName(_fromUtf8("is_a_trainer"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.is_a_trainer)
        self.eventsStackedWidget.addWidget(self.personEditor)
        self.triggerEditor = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.triggerEditor.sizePolicy().hasHeightForWidth())
        self.triggerEditor.setSizePolicy(sizePolicy)
        self.triggerEditor.setObjectName(_fromUtf8("triggerEditor"))
        self.formLayout_3 = QtGui.QFormLayout(self.triggerEditor)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_3 = QtGui.QLabel(self.triggerEditor)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self._4 = QtGui.QHBoxLayout()
        self._4.setObjectName(_fromUtf8("_4"))
        self.t_x = QtGui.QLineEdit(self.triggerEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_x.sizePolicy().hasHeightForWidth())
        self.t_x.setSizePolicy(sizePolicy)
        self.t_x.setMaximumSize(QtCore.QSize(40, 16777215))
        self.t_x.setObjectName(_fromUtf8("t_x"))
        self._4.addWidget(self.t_x)
        self.t_y = QtGui.QLineEdit(self.triggerEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_y.sizePolicy().hasHeightForWidth())
        self.t_y.setSizePolicy(sizePolicy)
        self.t_y.setMaximumSize(QtCore.QSize(40, 16777215))
        self.t_y.setObjectName(_fromUtf8("t_y"))
        self._4.addWidget(self.t_y)
        self.formLayout_3.setLayout(1, QtGui.QFormLayout.FieldRole, self._4)
        self.label_2 = QtGui.QLabel(self.triggerEditor)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.t_unknown1 = QtGui.QLineEdit(self.triggerEditor)
        self.t_unknown1.setObjectName(_fromUtf8("t_unknown1"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.t_unknown1)
        self.label_6 = QtGui.QLabel(self.triggerEditor)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_6)
        self.t_var_num = QtGui.QLineEdit(self.triggerEditor)
        self.t_var_num.setObjectName(_fromUtf8("t_var_num"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.t_var_num)
        self.label_8 = QtGui.QLabel(self.triggerEditor)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_29 = QtGui.QLabel(self.triggerEditor)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_29)
        self.t_var_val = QtGui.QLineEdit(self.triggerEditor)
        self.t_var_val.setObjectName(_fromUtf8("t_var_val"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.t_var_val)
        self._5 = QtGui.QHBoxLayout()
        self._5.setObjectName(_fromUtf8("_5"))
        self.t_unknown2 = QtGui.QLineEdit(self.triggerEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_unknown2.sizePolicy().hasHeightForWidth())
        self.t_unknown2.setSizePolicy(sizePolicy)
        self.t_unknown2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.t_unknown2.setObjectName(_fromUtf8("t_unknown2"))
        self._5.addWidget(self.t_unknown2)
        self.t_unknown3 = QtGui.QLineEdit(self.triggerEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_unknown3.sizePolicy().hasHeightForWidth())
        self.t_unknown3.setSizePolicy(sizePolicy)
        self.t_unknown3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.t_unknown3.setObjectName(_fromUtf8("t_unknown3"))
        self._5.addWidget(self.t_unknown3)
        self.formLayout_3.setLayout(5, QtGui.QFormLayout.FieldRole, self._5)
        self.t_script_offset = QtGui.QLineEdit(self.triggerEditor)
        self.t_script_offset.setObjectName(_fromUtf8("t_script_offset"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.FieldRole, self.t_script_offset)
        self.label_30 = QtGui.QLabel(self.triggerEditor)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_30)
        self.t_edit_script = QtGui.QPushButton(self.triggerEditor)
        self.t_edit_script.setObjectName(_fromUtf8("t_edit_script"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.FieldRole, self.t_edit_script)
        self.eventsStackedWidget.addWidget(self.triggerEditor)
        self.signpostEditor = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signpostEditor.sizePolicy().hasHeightForWidth())
        self.signpostEditor.setSizePolicy(sizePolicy)
        self.signpostEditor.setObjectName(_fromUtf8("signpostEditor"))
        self.formLayout_4 = QtGui.QFormLayout(self.signpostEditor)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_50 = QtGui.QLabel(self.signpostEditor)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_50)
        self.label_63 = QtGui.QLabel(self.signpostEditor)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_63)
        self._7 = QtGui.QHBoxLayout()
        self._7.setObjectName(_fromUtf8("_7"))
        self.s_x = QtGui.QLineEdit(self.signpostEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s_x.sizePolicy().hasHeightForWidth())
        self.s_x.setSizePolicy(sizePolicy)
        self.s_x.setMaximumSize(QtCore.QSize(40, 16777215))
        self.s_x.setObjectName(_fromUtf8("s_x"))
        self._7.addWidget(self.s_x)
        self.s_y = QtGui.QLineEdit(self.signpostEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s_y.sizePolicy().hasHeightForWidth())
        self.s_y.setSizePolicy(sizePolicy)
        self.s_y.setMaximumSize(QtCore.QSize(40, 16777215))
        self.s_y.setObjectName(_fromUtf8("s_y"))
        self._7.addWidget(self.s_y)
        self.formLayout_4.setLayout(1, QtGui.QFormLayout.FieldRole, self._7)
        self.label_65 = QtGui.QLabel(self.signpostEditor)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_65)
        self.s_talking_level = QtGui.QComboBox(self.signpostEditor)
        self.s_talking_level.setObjectName(_fromUtf8("s_talking_level"))
        self.s_talking_level.addItem(_fromUtf8(""))
        self.s_talking_level.addItem(_fromUtf8(""))
        self.s_talking_level.addItem(_fromUtf8(""))
        self.s_talking_level.addItem(_fromUtf8(""))
        self.s_talking_level.addItem(_fromUtf8(""))
        self.s_talking_level.addItem(_fromUtf8(""))
        self.s_talking_level.addItem(_fromUtf8(""))
        self.s_talking_level.addItem(_fromUtf8(""))
        self.s_talking_level.addItem(_fromUtf8(""))
        self.s_talking_level.addItem(_fromUtf8(""))
        self.s_talking_level.addItem(_fromUtf8(""))
        self.s_talking_level.addItem(_fromUtf8(""))
        self.s_talking_level.addItem(_fromUtf8(""))
        self.s_talking_level.addItem(_fromUtf8(""))
        self.s_talking_level.addItem(_fromUtf8(""))
        self.s_talking_level.addItem(_fromUtf8(""))
        self.s_talking_level.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.s_talking_level)
        self.signpost_stacked = QtGui.QStackedWidget(self.signpostEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signpost_stacked.sizePolicy().hasHeightForWidth())
        self.signpost_stacked.setSizePolicy(sizePolicy)
        self.signpost_stacked.setMinimumSize(QtCore.QSize(0, 0))
        self.signpost_stacked.setObjectName(_fromUtf8("signpost_stacked"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.formLayout_5 = QtGui.QFormLayout(self.page)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.s_script_offset = QtGui.QLineEdit(self.page)
        self.s_script_offset.setObjectName(_fromUtf8("s_script_offset"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.s_script_offset)
        self.label_64 = QtGui.QLabel(self.page)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_64)
        self.s_edit_script = QtGui.QPushButton(self.page)
        self.s_edit_script.setObjectName(_fromUtf8("s_edit_script"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.s_edit_script)
        self.signpost_stacked.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.formLayout_6 = QtGui.QFormLayout(self.page_2)
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_31 = QtGui.QLabel(self.page_2)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_31)
        self.s_item_id = QtGui.QLineEdit(self.page_2)
        self.s_item_id.setObjectName(_fromUtf8("s_item_id"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.s_item_id)
        self.label_32 = QtGui.QLabel(self.page_2)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_32)
        self.s_hidden_id = QtGui.QLineEdit(self.page_2)
        self.s_hidden_id.setObjectName(_fromUtf8("s_hidden_id"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.s_hidden_id)
        self.label_33 = QtGui.QLabel(self.page_2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_33)
        self.s_ammount = QtGui.QLineEdit(self.page_2)
        self.s_ammount.setObjectName(_fromUtf8("s_ammount"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.s_ammount)
        self.signpost_stacked.addWidget(self.page_2)
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.SpanningRole, self.signpost_stacked)
        self.label_66 = QtGui.QLabel(self.signpostEditor)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_66)
        self.s_type = QtGui.QComboBox(self.signpostEditor)
        self.s_type.setObjectName(_fromUtf8("s_type"))
        self.s_type.addItem(_fromUtf8(""))
        self.s_type.addItem(_fromUtf8(""))
        self.s_type.addItem(_fromUtf8(""))
        self.s_type.addItem(_fromUtf8(""))
        self.s_type.addItem(_fromUtf8(""))
        self.s_type.addItem(_fromUtf8(""))
        self.s_type.addItem(_fromUtf8(""))
        self.s_type.addItem(_fromUtf8(""))
        self.s_type.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.s_type)
        self.label_34 = QtGui.QLabel(self.signpostEditor)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_34)
        self._9 = QtGui.QHBoxLayout()
        self._9.setObjectName(_fromUtf8("_9"))
        self.s_unknown1 = QtGui.QLineEdit(self.signpostEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s_unknown1.sizePolicy().hasHeightForWidth())
        self.s_unknown1.setSizePolicy(sizePolicy)
        self.s_unknown1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.s_unknown1.setObjectName(_fromUtf8("s_unknown1"))
        self._9.addWidget(self.s_unknown1)
        self.s_unknown2 = QtGui.QLineEdit(self.signpostEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s_unknown2.sizePolicy().hasHeightForWidth())
        self.s_unknown2.setSizePolicy(sizePolicy)
        self.s_unknown2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.s_unknown2.setObjectName(_fromUtf8("s_unknown2"))
        self._9.addWidget(self.s_unknown2)
        self.formLayout_4.setLayout(4, QtGui.QFormLayout.FieldRole, self._9)
        self.eventsStackedWidget.addWidget(self.signpostEditor)
        self.verticalLayout_2.addWidget(self.eventsStackedWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 1, 1, 1)
        self.tabWidget.addTab(self.eventsTab, _fromUtf8(""))
        self.HeaderTab = QtGui.QWidget()
        self.HeaderTab.setObjectName(_fromUtf8("HeaderTab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.HeaderTab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.groupBox = QtGui.QGroupBox(self.HeaderTab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.song_index = QtGui.QLineEdit(self.groupBox)
        self.song_index.setObjectName(_fromUtf8("song_index"))
        self.gridLayout_12.addWidget(self.song_index, 5, 1, 1, 1)
        self.con_data_ptr = QtGui.QLineEdit(self.groupBox)
        self.con_data_ptr.setObjectName(_fromUtf8("con_data_ptr"))
        self.gridLayout_12.addWidget(self.con_data_ptr, 4, 1, 1, 1)
        self.label_103 = QtGui.QLabel(self.groupBox)
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.gridLayout_12.addWidget(self.label_103, 4, 0, 1, 1)
        self.label_42 = QtGui.QLabel(self.groupBox)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_12.addWidget(self.label_42, 7, 0, 1, 1)
        self.label_105 = QtGui.QLabel(self.groupBox)
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.gridLayout_12.addWidget(self.label_105, 1, 0, 1, 1)
        self.m_ptr_index = QtGui.QLineEdit(self.groupBox)
        self.m_ptr_index.setObjectName(_fromUtf8("m_ptr_index"))
        self.gridLayout_12.addWidget(self.m_ptr_index, 1, 1, 1, 1)
        self.weather_type = QtGui.QLineEdit(self.groupBox)
        self.weather_type.setObjectName(_fromUtf8("weather_type"))
        self.gridLayout_12.addWidget(self.weather_type, 12, 1, 1, 1)
        self.label_95 = QtGui.QLabel(self.groupBox)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.gridLayout_12.addWidget(self.label_95, 14, 0, 1, 1)
        self.battle_type = QtGui.QLineEdit(self.groupBox)
        self.battle_type.setObjectName(_fromUtf8("battle_type"))
        self.gridLayout_12.addWidget(self.battle_type, 14, 1, 1, 1)
        self.label_104 = QtGui.QLabel(self.groupBox)
        self.label_104.setObjectName(_fromUtf8("label_104"))
        self.gridLayout_12.addWidget(self.label_104, 5, 0, 1, 1)
        self.show_label = QtGui.QCheckBox(self.groupBox)
        self.show_label.setText(_fromUtf8(""))
        self.show_label.setObjectName(_fromUtf8("show_label"))
        self.gridLayout_12.addWidget(self.show_label, 7, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem1, 15, 1, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBox)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_12.addWidget(self.label_36, 0, 0, 1, 1)
        self.label_39 = QtGui.QLabel(self.groupBox)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_12.addWidget(self.label_39, 11, 0, 1, 1)
        self.label_41 = QtGui.QLabel(self.groupBox)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_12.addWidget(self.label_41, 10, 0, 1, 1)
        self.label_38 = QtGui.QLabel(self.groupBox)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_12.addWidget(self.label_38, 2, 0, 1, 1)
        self.e_data_ptr = QtGui.QLineEdit(self.groupBox)
        self.e_data_ptr.setObjectName(_fromUtf8("e_data_ptr"))
        self.gridLayout_12.addWidget(self.e_data_ptr, 2, 1, 1, 1)
        self.label_37 = QtGui.QLabel(self.groupBox)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_12.addWidget(self.label_37, 3, 0, 1, 1)
        self.ls_ptr = QtGui.QLineEdit(self.groupBox)
        self.ls_ptr.setObjectName(_fromUtf8("ls_ptr"))
        self.gridLayout_12.addWidget(self.ls_ptr, 3, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.groupBox)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_12.addWidget(self.label_35, 6, 0, 1, 1)
        self.label_index = QtGui.QLineEdit(self.groupBox)
        self.label_index.setObjectName(_fromUtf8("label_index"))
        self.gridLayout_12.addWidget(self.label_index, 6, 1, 1, 1)
        self.map_type = QtGui.QLineEdit(self.groupBox)
        self.map_type.setObjectName(_fromUtf8("map_type"))
        self.gridLayout_12.addWidget(self.map_type, 10, 1, 1, 1)
        self.m_data_ptr = QtGui.QLineEdit(self.groupBox)
        self.m_data_ptr.setObjectName(_fromUtf8("m_data_ptr"))
        self.gridLayout_12.addWidget(self.m_data_ptr, 0, 1, 1, 1)
        self.label_40 = QtGui.QLabel(self.groupBox)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_12.addWidget(self.label_40, 12, 0, 1, 1)
        self.is_cave = QtGui.QCheckBox(self.groupBox)
        self.is_cave.setText(_fromUtf8(""))
        self.is_cave.setObjectName(_fromUtf8("is_cave"))
        self.gridLayout_12.addWidget(self.is_cave, 11, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.HeaderTab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.t1_ptr = QtGui.QLineEdit(self.groupBox_2)
        self.t1_ptr.setObjectName(_fromUtf8("t1_ptr"))
        self.gridLayout_13.addWidget(self.t1_ptr, 4, 2, 1, 1)
        self.label_102 = QtGui.QLabel(self.groupBox_2)
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.gridLayout_13.addWidget(self.label_102, 5, 0, 1, 1)
        self.label_96 = QtGui.QLabel(self.groupBox_2)
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.gridLayout_13.addWidget(self.label_96, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem2, 7, 2, 1, 1)
        self.t2_ptr = QtGui.QLineEdit(self.groupBox_2)
        self.t2_ptr.setObjectName(_fromUtf8("t2_ptr"))
        self.gridLayout_13.addWidget(self.t2_ptr, 5, 2, 1, 1)
        self.label_99 = QtGui.QLabel(self.groupBox_2)
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.gridLayout_13.addWidget(self.label_99, 6, 0, 1, 1)
        self.label_100 = QtGui.QLabel(self.groupBox_2)
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.gridLayout_13.addWidget(self.label_100, 3, 0, 1, 1)
        self.border_info_ptr = QtGui.QLineEdit(self.groupBox_2)
        self.border_info_ptr.setObjectName(_fromUtf8("border_info_ptr"))
        self.gridLayout_13.addWidget(self.border_info_ptr, 6, 2, 1, 1)
        self.label_101 = QtGui.QLabel(self.groupBox_2)
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.gridLayout_13.addWidget(self.label_101, 4, 0, 1, 1)
        self.tilemap_ptr = QtGui.QLineEdit(self.groupBox_2)
        self.tilemap_ptr.setObjectName(_fromUtf8("tilemap_ptr"))
        self.gridLayout_13.addWidget(self.tilemap_ptr, 3, 2, 1, 1)
        self._18 = QtGui.QHBoxLayout()
        self._18.setObjectName(_fromUtf8("_18"))
        self.label_97 = QtGui.QLabel(self.groupBox_2)
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self._18.addWidget(self.label_97)
        self.map_w = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_w.sizePolicy().hasHeightForWidth())
        self.map_w.setSizePolicy(sizePolicy)
        self.map_w.setMaximumSize(QtCore.QSize(40, 16777215))
        self.map_w.setObjectName(_fromUtf8("map_w"))
        self._18.addWidget(self.map_w)
        self.label_98 = QtGui.QLabel(self.groupBox_2)
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self._18.addWidget(self.label_98)
        self.map_h = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_h.sizePolicy().hasHeightForWidth())
        self.map_h.setSizePolicy(sizePolicy)
        self.map_h.setMaximumSize(QtCore.QSize(40, 16777215))
        self.map_h.setObjectName(_fromUtf8("map_h"))
        self._18.addWidget(self.map_h)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._18.addItem(spacerItem3)
        self.gridLayout_13.addLayout(self._18, 0, 2, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.tabWidget.addTab(self.HeaderTab, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lscriptsLayout = QtGui.QVBoxLayout()
        self.lscriptsLayout.setObjectName(_fromUtf8("lscriptsLayout"))
        self.verticalLayout_3.addLayout(self.lscriptsLayout)
        self.addLevelScriptButton = QtGui.QPushButton(self.tab)
        self.addLevelScriptButton.setEnabled(False)
        self.addLevelScriptButton.setObjectName(_fromUtf8("addLevelScriptButton"))
        self.verticalLayout_3.addWidget(self.addLevelScriptButton)
        self.gridLayout_9.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.PalTab = QtGui.QWidget()
        self.PalTab.setEnabled(False)
        self.PalTab.setObjectName(_fromUtf8("PalTab"))
        self.gridLayout_7 = QtGui.QGridLayout(self.PalTab)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.groupBox_3 = QtGui.QGroupBox(self.PalTab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_8.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_8.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_48 = QtGui.QLabel(self.groupBox_3)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_8.addWidget(self.label_48, 4, 0, 1, 1)
        self.label_49 = QtGui.QLabel(self.groupBox_3)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_8.addWidget(self.label_49, 5, 0, 1, 1)
        self.label_45 = QtGui.QLabel(self.groupBox_3)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_8.addWidget(self.label_45, 2, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_8.addWidget(self.checkBox, 4, 1, 1, 1)
        self.label_44 = QtGui.QLabel(self.groupBox_3)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_8.addWidget(self.label_44, 1, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_8.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_2.setText(_fromUtf8(""))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_8.addWidget(self.checkBox_2, 5, 1, 1, 1)
        self.label_47 = QtGui.QLabel(self.groupBox_3)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_8.addWidget(self.label_47, 3, 0, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_8.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.groupBox_3)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_8.addWidget(self.label_46, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout_8.addLayout(self.horizontalLayout_5, 7, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tile1 = QtGui.QGraphicsView(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tile1.sizePolicy().hasHeightForWidth())
        self.tile1.setSizePolicy(sizePolicy)
        self.tile1.setMaximumSize(QtCore.QSize(64, 64))
        self.tile1.setObjectName(_fromUtf8("tile1"))
        self.horizontalLayout_4.addWidget(self.tile1)
        self.tile2 = QtGui.QGraphicsView(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tile2.sizePolicy().hasHeightForWidth())
        self.tile2.setSizePolicy(sizePolicy)
        self.tile2.setMaximumSize(QtCore.QSize(64, 64))
        self.tile2.setObjectName(_fromUtf8("tile2"))
        self.horizontalLayout_4.addWidget(self.tile2)
        self.gridLayout_8.addLayout(self.horizontalLayout_4, 7, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem4, 8, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_8)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_43 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.horizontalLayout.addWidget(self.label_43)
        self.comboBox = QtGui.QComboBox(self.groupBox_4)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tileset = QtGui.QGraphicsView(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tileset.sizePolicy().hasHeightForWidth())
        self.tileset.setSizePolicy(sizePolicy)
        self.tileset.setMinimumSize(QtCore.QSize(160, 0))
        self.tileset.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tileset.setObjectName(_fromUtf8("tileset"))
        self.verticalLayout.addWidget(self.tileset)
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.gridLayout_7.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.edPalette = QtGui.QGraphicsView(self.PalTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edPalette.sizePolicy().hasHeightForWidth())
        self.edPalette.setSizePolicy(sizePolicy)
        self.edPalette.setMinimumSize(QtCore.QSize(160, 0))
        self.edPalette.setMaximumSize(QtCore.QSize(200, 16777215))
        self.edPalette.setObjectName(_fromUtf8("edPalette"))
        self.gridLayout_7.addWidget(self.edPalette, 0, 0, 1, 1)
        self.tabWidget.addTab(self.PalTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 988, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_ROM = QtGui.QAction(MainWindow)
        self.actionLoad_ROM.setObjectName(_fromUtf8("actionLoad_ROM"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionChoose_script_editor = QtGui.QAction(MainWindow)
        self.actionChoose_script_editor.setObjectName(_fromUtf8("actionChoose_script_editor"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionAdd_new_banks = QtGui.QAction(MainWindow)
        self.actionAdd_new_banks.setObjectName(_fromUtf8("actionAdd_new_banks"))
        self.menuFile.addAction(self.actionLoad_ROM)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuEdit.addAction(self.actionChoose_script_editor)
        self.menuTools.addAction(self.actionAdd_new_banks)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.eventsStackedWidget.setCurrentIndex(0)
        self.signpost_stacked.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Blue Spider", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mapTab), _translate("MainWindow", "Map", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.movPermissionsTab), _translate("MainWindow", "Movement Permissions", None))
        self.EventsBox.setTitle(_translate("MainWindow", "Add events", None))
        self.label_4.setText(_translate("MainWindow", "People:", None))
        self.addTriggerButton.setText(_translate("MainWindow", "+", None))
        self.num_of_signposts.setText(_translate("MainWindow", "0", None))
        self.label_5.setText(_translate("MainWindow", "Triggers:", None))
        self.label.setText(_translate("MainWindow", "Warps: ", None))
        self.num_of_warps.setText(_translate("MainWindow", "0", None))
        self.num_of_people.setText(_translate("MainWindow", "0", None))
        self.num_of_triggers.setText(_translate("MainWindow", "0", None))
        self.label_7.setText(_translate("MainWindow", "Signposts:", None))
        self.addSignpostButton.setText(_translate("MainWindow", "+", None))
        self.addPersonButton.setText(_translate("MainWindow", "+", None))
        self.remWarpButton.setText(_translate("MainWindow", "-", None))
        self.addWarpButton.setText(_translate("MainWindow", "+", None))
        self.remPersonButton.setText(_translate("MainWindow", "-", None))
        self.remTriggerButton.setText(_translate("MainWindow", "-", None))
        self.remSignpostButton.setText(_translate("MainWindow", "-", None))
        self.label_10.setText(_translate("MainWindow", "X/Y", None))
        self.label_11.setText(_translate("MainWindow", "Unknown", None))
        self.label_12.setText(_translate("MainWindow", "Bank num.", None))
        self.label_13.setText(_translate("MainWindow", "Map num.", None))
        self.label_14.setText(_translate("MainWindow", "Warp num.", None))
        self.warpGoToMapButton.setText(_translate("MainWindow", "Go to map", None))
        self.openInEmulatorButton.setText(_translate("MainWindow", "Open in emulator", None))
        self.label_16.setText(_translate("MainWindow", "Person num.", None))
        self.label_17.setText(_translate("MainWindow", "Sprite num. (dec)", None))
        self.label_18.setText(_translate("MainWindow", "Unknown", None))
        self.label_15.setText(_translate("MainWindow", "X/Y", None))
        self.label_19.setText(_translate("MainWindow", "Unknown", None))
        self.label_20.setText(_translate("MainWindow", "Mov. type", None))
        self.p_mov_type.setItemText(0, _translate("MainWindow", "No movement", None))
        self.p_mov_type.setItemText(1, _translate("MainWindow", "Look around", None))
        self.p_mov_type.setItemText(2, _translate("MainWindow", "Walk around", None))
        self.p_mov_type.setItemText(3, _translate("MainWindow", "Walk up and down", None))
        self.p_mov_type.setItemText(4, _translate("MainWindow", "Walk up and down", None))
        self.p_mov_type.setItemText(5, _translate("MainWindow", "Walk left and right", None))
        self.p_mov_type.setItemText(6, _translate("MainWindow", "Walk left and right", None))
        self.p_mov_type.setItemText(7, _translate("MainWindow", "Look up", None))
        self.p_mov_type.setItemText(8, _translate("MainWindow", "Look down", None))
        self.p_mov_type.setItemText(9, _translate("MainWindow", "Look left", None))
        self.p_mov_type.setItemText(10, _translate("MainWindow", "Look right", None))
        self.p_mov_type.setItemText(11, _translate("MainWindow", "Do NOT use", None))
        self.p_mov_type.setItemText(12, _translate("MainWindow", "Hidden", None))
        self.p_mov_type.setItemText(13, _translate("MainWindow", "Look up and down", None))
        self.p_mov_type.setItemText(14, _translate("MainWindow", "Look left and right", None))
        self.p_mov_type.setItemText(15, _translate("MainWindow", "Look up and left", None))
        self.p_mov_type.setItemText(16, _translate("MainWindow", "Look up and rigth", None))
        self.p_mov_type.setItemText(17, _translate("MainWindow", "Look down and left", None))
        self.p_mov_type.setItemText(18, _translate("MainWindow", "Look down and right", None))
        self.p_mov_type.setItemText(19, _translate("MainWindow", "Look up, down and left", None))
        self.p_mov_type.setItemText(20, _translate("MainWindow", "Look up, down and right", None))
        self.p_mov_type.setItemText(21, _translate("MainWindow", "Look up, left and right", None))
        self.p_mov_type.setItemText(22, _translate("MainWindow", "Look down, left and right", None))
        self.p_mov_type.setItemText(23, _translate("MainWindow", "Look around counterclockwise", None))
        self.p_mov_type.setItemText(24, _translate("MainWindow", "Look around clockwise", None))
        self.p_mov_type.setItemText(25, _translate("MainWindow", "Run up and down", None))
        self.p_mov_type.setItemText(26, _translate("MainWindow", "Run up and down", None))
        self.p_mov_type.setItemText(27, _translate("MainWindow", "Run left and right", None))
        self.p_mov_type.setItemText(28, _translate("MainWindow", "Run left and right", None))
        self.p_mov_type.setItemText(29, _translate("MainWindow", "Run up, right, left and down", None))
        self.p_mov_type.setItemText(30, _translate("MainWindow", "Run right, left, down and up", None))
        self.p_mov_type.setItemText(31, _translate("MainWindow", "Run down, up, right and left", None))
        self.p_mov_type.setItemText(32, _translate("MainWindow", "Run left, down, up and right", None))
        self.p_mov_type.setItemText(33, _translate("MainWindow", "Run up, left, right and down", None))
        self.p_mov_type.setItemText(34, _translate("MainWindow", "Run left, right down and up", None))
        self.p_mov_type.setItemText(35, _translate("MainWindow", "Run down, up, left and right", None))
        self.p_mov_type.setItemText(36, _translate("MainWindow", "Run right, down, up and left", None))
        self.p_mov_type.setItemText(37, _translate("MainWindow", "Run left, up, down and right", None))
        self.p_mov_type.setItemText(38, _translate("MainWindow", "26", None))
        self.p_mov_type.setItemText(39, _translate("MainWindow", "27", None))
        self.p_mov_type.setItemText(40, _translate("MainWindow", "28", None))
        self.p_mov_type.setItemText(41, _translate("MainWindow", "29", None))
        self.p_mov_type.setItemText(42, _translate("MainWindow", "2A", None))
        self.p_mov_type.setItemText(43, _translate("MainWindow", "2B", None))
        self.p_mov_type.setItemText(44, _translate("MainWindow", "2C", None))
        self.p_mov_type.setItemText(45, _translate("MainWindow", "2D", None))
        self.p_mov_type.setItemText(46, _translate("MainWindow", "2E", None))
        self.p_mov_type.setItemText(47, _translate("MainWindow", "2F", None))
        self.p_mov_type.setItemText(48, _translate("MainWindow", "30", None))
        self.p_mov_type.setItemText(49, _translate("MainWindow", "31", None))
        self.p_mov_type.setItemText(50, _translate("MainWindow", "32", None))
        self.p_mov_type.setItemText(51, _translate("MainWindow", "33", None))
        self.p_mov_type.setItemText(52, _translate("MainWindow", "34", None))
        self.p_mov_type.setItemText(53, _translate("MainWindow", "35", None))
        self.p_mov_type.setItemText(54, _translate("MainWindow", "36", None))
        self.p_mov_type.setItemText(55, _translate("MainWindow", "37", None))
        self.p_mov_type.setItemText(56, _translate("MainWindow", "38", None))
        self.p_mov_type.setItemText(57, _translate("MainWindow", "39", None))
        self.p_mov_type.setItemText(58, _translate("MainWindow", "3A", None))
        self.p_mov_type.setItemText(59, _translate("MainWindow", "3B", None))
        self.p_mov_type.setItemText(60, _translate("MainWindow", "3C", None))
        self.p_mov_type.setItemText(61, _translate("MainWindow", "3D", None))
        self.p_mov_type.setItemText(62, _translate("MainWindow", "3E", None))
        self.p_mov_type.setItemText(63, _translate("MainWindow", "3F", None))
        self.p_mov_type.setItemText(64, _translate("MainWindow", "40", None))
        self.p_mov_type.setItemText(65, _translate("MainWindow", "41", None))
        self.p_mov_type.setItemText(66, _translate("MainWindow", "42", None))
        self.p_mov_type.setItemText(67, _translate("MainWindow", "43", None))
        self.p_mov_type.setItemText(68, _translate("MainWindow", "44", None))
        self.p_mov_type.setItemText(69, _translate("MainWindow", "45", None))
        self.p_mov_type.setItemText(70, _translate("MainWindow", "46", None))
        self.p_mov_type.setItemText(71, _translate("MainWindow", "47", None))
        self.p_mov_type.setItemText(72, _translate("MainWindow", "48", None))
        self.p_mov_type.setItemText(73, _translate("MainWindow", "49", None))
        self.p_mov_type.setItemText(74, _translate("MainWindow", "4A", None))
        self.p_mov_type.setItemText(75, _translate("MainWindow", "4B", None))
        self.p_mov_type.setItemText(76, _translate("MainWindow", "4C", None))
        self.p_mov_type.setItemText(77, _translate("MainWindow", "4D", None))
        self.p_mov_type.setItemText(78, _translate("MainWindow", "4E", None))
        self.p_mov_type.setItemText(79, _translate("MainWindow", "4F", None))
        self.p_mov_type.setItemText(80, _translate("MainWindow", "50", None))
        self.label_21.setText(_translate("MainWindow", "Movement", None))
        self.label_22.setText(_translate("MainWindow", "Unknown", None))
        self.label_23.setText(_translate("MainWindow", "Is a trainer", None))
        self.label_24.setText(_translate("MainWindow", "Unknown", None))
        self.label_25.setText(_translate("MainWindow", "View radius", None))
        self.label_26.setText(_translate("MainWindow", "Script offset", None))
        self.label_27.setText(_translate("MainWindow", "Flag", None))
        self.label_28.setText(_translate("MainWindow", "Unknown", None))
        self.p_edit_script.setText(_translate("MainWindow", "Edit Script", None))
        self.label_9.setText(_translate("MainWindow", "Sprite", None))
        self.label_3.setText(_translate("MainWindow", "X/Y", None))
        self.label_2.setText(_translate("MainWindow", "Unknown", None))
        self.label_6.setText(_translate("MainWindow", "Var Number", None))
        self.label_8.setText(_translate("MainWindow", "Var value", None))
        self.label_29.setText(_translate("MainWindow", "Unknown", None))
        self.label_30.setText(_translate("MainWindow", "Script offset", None))
        self.t_edit_script.setText(_translate("MainWindow", "Edit Script", None))
        self.label_50.setText(_translate("MainWindow", "Signpost", None))
        self.label_63.setText(_translate("MainWindow", "X/Y", None))
        self.label_65.setText(_translate("MainWindow", "Talking level", None))
        self.s_talking_level.setItemText(0, _translate("MainWindow", "Always", None))
        self.s_talking_level.setItemText(1, _translate("MainWindow", "0 Surf", None))
        self.s_talking_level.setItemText(2, _translate("MainWindow", "1", None))
        self.s_talking_level.setItemText(3, _translate("MainWindow", "2 Normal", None))
        self.s_talking_level.setItemText(4, _translate("MainWindow", "3", None))
        self.s_talking_level.setItemText(5, _translate("MainWindow", "4", None))
        self.s_talking_level.setItemText(6, _translate("MainWindow", "5", None))
        self.s_talking_level.setItemText(7, _translate("MainWindow", "6", None))
        self.s_talking_level.setItemText(8, _translate("MainWindow", "7", None))
        self.s_talking_level.setItemText(9, _translate("MainWindow", "8", None))
        self.s_talking_level.setItemText(10, _translate("MainWindow", "9", None))
        self.s_talking_level.setItemText(11, _translate("MainWindow", "A", None))
        self.s_talking_level.setItemText(12, _translate("MainWindow", "B", None))
        self.s_talking_level.setItemText(13, _translate("MainWindow", "C", None))
        self.s_talking_level.setItemText(14, _translate("MainWindow", "D", None))
        self.s_talking_level.setItemText(15, _translate("MainWindow", "E", None))
        self.s_talking_level.setItemText(16, _translate("MainWindow", "F", None))
        self.label_64.setText(_translate("MainWindow", "Script Offset", None))
        self.s_edit_script.setText(_translate("MainWindow", "Edit Script", None))
        self.label_31.setText(_translate("MainWindow", "Item Id", None))
        self.label_32.setText(_translate("MainWindow", "Hidden Id", None))
        self.label_33.setText(_translate("MainWindow", "Ammount", None))
        self.label_66.setText(_translate("MainWindow", "Type", None))
        self.s_type.setItemText(0, _translate("MainWindow", "Script", None))
        self.s_type.setItemText(1, _translate("MainWindow", "Script if player is facing up", None))
        self.s_type.setItemText(2, _translate("MainWindow", "Script if player is facing down", None))
        self.s_type.setItemText(3, _translate("MainWindow", "Script if player is facing right", None))
        self.s_type.setItemText(4, _translate("MainWindow", "Script if player is facing left", None))
        self.s_type.setItemText(5, _translate("MainWindow", "Hidden item", None))
        self.s_type.setItemText(6, _translate("MainWindow", "Hidden item", None))
        self.s_type.setItemText(7, _translate("MainWindow", "Hidden item", None))
        self.s_type.setItemText(8, _translate("MainWindow", "Secret base", None))
        self.label_34.setText(_translate("MainWindow", "Unknown", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.eventsTab), _translate("MainWindow", "Events", None))
        self.groupBox.setTitle(_translate("MainWindow", "Map Header", None))
        self.label_103.setText(_translate("MainWindow", "Connection Data Address", None))
        self.label_42.setText(_translate("MainWindow", "Show Label on Entering", None))
        self.label_105.setText(_translate("MainWindow", "Map Address Index", None))
        self.label_95.setText(_translate("MainWindow", "Battle Type", None))
        self.label_104.setText(_translate("MainWindow", "Song Index", None))
        self.label_36.setText(_translate("MainWindow", "Map Data Address", None))
        self.label_39.setText(_translate("MainWindow", "Is a Cave", None))
        self.label_41.setText(_translate("MainWindow", "Map Type Number", None))
        self.label_38.setText(_translate("MainWindow", "Event Data Address", None))
        self.label_37.setText(_translate("MainWindow", "Level script Address", None))
        self.label_35.setText(_translate("MainWindow", "Label Index", None))
        self.label_40.setText(_translate("MainWindow", "Weather Type Number", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Map Data", None))
        self.label_102.setText(_translate("MainWindow", "Local Tileset Address", None))
        self.label_96.setText(_translate("MainWindow", "Dimensions:", None))
        self.label_99.setText(_translate("MainWindow", "Border Info Address", None))
        self.label_100.setText(_translate("MainWindow", "Tilemap Address", None))
        self.label_101.setText(_translate("MainWindow", "Global Tileset Address", None))
        self.label_97.setText(_translate("MainWindow", "Width", None))
        self.label_98.setText(_translate("MainWindow", "Height", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.HeaderTab), _translate("MainWindow", "Header", None))
        self.addLevelScriptButton.setText(_translate("MainWindow", "+", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Level Scripts", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Properties", None))
        self.label_48.setText(_translate("MainWindow", "Horizontal Flip", None))
        self.label_49.setText(_translate("MainWindow", "Vertical Flip", None))
        self.label_45.setText(_translate("MainWindow", "Background", None))
        self.label_44.setText(_translate("MainWindow", "Behavior 2", None))
        self.label_47.setText(_translate("MainWindow", "Background 2", None))
        self.label_46.setText(_translate("MainWindow", "Behavior", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Tileset", None))
        self.label_43.setText(_translate("MainWindow", "Palette", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "0", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "1", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "2", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "3", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "4", None))
        self.comboBox.setItemText(5, _translate("MainWindow", "5", None))
        self.comboBox.setItemText(6, _translate("MainWindow", "6", None))
        self.comboBox.setItemText(7, _translate("MainWindow", "7", None))
        self.comboBox.setItemText(8, _translate("MainWindow", "8", None))
        self.comboBox.setItemText(9, _translate("MainWindow", "9", None))
        self.comboBox.setItemText(10, _translate("MainWindow", "10", None))
        self.comboBox.setItemText(11, _translate("MainWindow", "11", None))
        self.comboBox.setItemText(12, _translate("MainWindow", "12", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PalTab), _translate("MainWindow", "Tilemap Palette", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.actionLoad_ROM.setText(_translate("MainWindow", "Load ROM", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionChoose_script_editor.setText(_translate("MainWindow", "Select script editor", None))
        self.actionSave_As.setText(_translate("MainWindow", "Save As", None))
        self.actionAdd_new_banks.setText(_translate("MainWindow", "Add new banks", None))

