# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapped.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1109, 706)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMinimumSize(QtCore.QSize(70, 0))
        self.treeView.setMaximumSize(QtCore.QSize(170, 16777215))
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeView.setIndentation(10)
        self.treeView.setObjectName("treeView")
        self.gridLayout.addWidget(self.treeView, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.mapTab = QtWidgets.QWidget()
        self.mapTab.setObjectName("mapTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mapTab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.map = QtWidgets.QGraphicsView(self.mapTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map.sizePolicy().hasHeightForWidth())
        self.map.setSizePolicy(sizePolicy)
        self.map.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.map.setObjectName("map")
        self.gridLayout_2.addWidget(self.map, 0, 0, 1, 1)
        self.palette = QtWidgets.QGraphicsView(self.mapTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.palette.sizePolicy().hasHeightForWidth())
        self.palette.setSizePolicy(sizePolicy)
        self.palette.setMinimumSize(QtCore.QSize(160, 0))
        self.palette.setMaximumSize(QtCore.QSize(200, 16777215))
        self.palette.setObjectName("palette")
        self.gridLayout_2.addWidget(self.palette, 0, 1, 1, 1)
        self.tabWidget.addTab(self.mapTab, "")
        self.movPermissionsTab = QtWidgets.QWidget()
        self.movPermissionsTab.setObjectName("movPermissionsTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.movPermissionsTab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.movPermissionsMap = QtWidgets.QGraphicsView(self.movPermissionsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movPermissionsMap.sizePolicy().hasHeightForWidth())
        self.movPermissionsMap.setSizePolicy(sizePolicy)
        self.movPermissionsMap.setObjectName("movPermissionsMap")
        self.gridLayout_3.addWidget(self.movPermissionsMap, 0, 0, 1, 1)
        self.MovPermissionsPalette = QtWidgets.QGraphicsView(self.movPermissionsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MovPermissionsPalette.sizePolicy().hasHeightForWidth())
        self.MovPermissionsPalette.setSizePolicy(sizePolicy)
        self.MovPermissionsPalette.setMinimumSize(QtCore.QSize(160, 0))
        self.MovPermissionsPalette.setMaximumSize(QtCore.QSize(200, 16777215))
        self.MovPermissionsPalette.setObjectName("MovPermissionsPalette")
        self.gridLayout_3.addWidget(self.MovPermissionsPalette, 0, 1, 1, 1)
        self.tabWidget.addTab(self.movPermissionsTab, "")
        self.eventsTab = QtWidgets.QWidget()
        self.eventsTab.setEnabled(True)
        self.eventsTab.setObjectName("eventsTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.eventsTab)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.eventMap = QtWidgets.QGraphicsView(self.eventsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventMap.sizePolicy().hasHeightForWidth())
        self.eventMap.setSizePolicy(sizePolicy)
        self.eventMap.setObjectName("eventMap")
        self.gridLayout_4.addWidget(self.eventMap, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.eventsTab)
        self.scrollArea.setMinimumSize(QtCore.QSize(270, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(280, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 270, 945))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(270, 16777215))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.eventSelectorCombo = QtWidgets.QComboBox(self.groupBox_5)
        self.eventSelectorCombo.setObjectName("eventSelectorCombo")
        self.eventSelectorCombo.addItem("")
        self.eventSelectorCombo.addItem("")
        self.eventSelectorCombo.addItem("")
        self.eventSelectorCombo.addItem("")
        self.gridLayout_10.addWidget(self.eventSelectorCombo, 0, 0, 1, 1)
        self.eventSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.eventSpinBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.eventSpinBox.setObjectName("eventSpinBox")
        self.gridLayout_10.addWidget(self.eventSpinBox, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.eventsStackedWidget = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventsStackedWidget.sizePolicy().hasHeightForWidth())
        self.eventsStackedWidget.setSizePolicy(sizePolicy)
        self.eventsStackedWidget.setObjectName("eventsStackedWidget")
        self.emptyEditor = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emptyEditor.sizePolicy().hasHeightForWidth())
        self.emptyEditor.setSizePolicy(sizePolicy)
        self.emptyEditor.setObjectName("emptyEditor")
        self.eventsStackedWidget.addWidget(self.emptyEditor)
        self.warpEditor = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warpEditor.sizePolicy().hasHeightForWidth())
        self.warpEditor.setSizePolicy(sizePolicy)
        self.warpEditor.setObjectName("warpEditor")
        self.formLayout_2 = QtWidgets.QFormLayout(self.warpEditor)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtWidgets.QLabel(self.warpEditor)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self._8 = QtWidgets.QHBoxLayout()
        self._8.setObjectName("_8")
        self.w_x = QtWidgets.QLineEdit(self.warpEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_x.sizePolicy().hasHeightForWidth())
        self.w_x.setSizePolicy(sizePolicy)
        self.w_x.setMaximumSize(QtCore.QSize(40, 16777215))
        self.w_x.setObjectName("w_x")
        self._8.addWidget(self.w_x)
        self.w_y = QtWidgets.QLineEdit(self.warpEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_y.sizePolicy().hasHeightForWidth())
        self.w_y.setSizePolicy(sizePolicy)
        self.w_y.setMaximumSize(QtCore.QSize(40, 16777215))
        self.w_y.setObjectName("w_y")
        self._8.addWidget(self.w_y)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self._8)
        self.label_11 = QtWidgets.QLabel(self.warpEditor)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.w_unknown1 = QtWidgets.QLineEdit(self.warpEditor)
        self.w_unknown1.setObjectName("w_unknown1")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.w_unknown1)
        self.label_12 = QtWidgets.QLabel(self.warpEditor)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.w_bank_n = QtWidgets.QLineEdit(self.warpEditor)
        self.w_bank_n.setObjectName("w_bank_n")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.w_bank_n)
        self.label_13 = QtWidgets.QLabel(self.warpEditor)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.w_map_n = QtWidgets.QLineEdit(self.warpEditor)
        self.w_map_n.setObjectName("w_map_n")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.w_map_n)
        self.label_14 = QtWidgets.QLabel(self.warpEditor)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.w_warp_n = QtWidgets.QLineEdit(self.warpEditor)
        self.w_warp_n.setObjectName("w_warp_n")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.w_warp_n)
        self.warpGoToMapButton = QtWidgets.QPushButton(self.warpEditor)
        self.warpGoToMapButton.setObjectName("warpGoToMapButton")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.warpGoToMapButton)
        self.openInEmulatorButton = QtWidgets.QPushButton(self.warpEditor)
        self.openInEmulatorButton.setEnabled(False)
        self.openInEmulatorButton.setObjectName("openInEmulatorButton")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.openInEmulatorButton)
        self.eventsStackedWidget.addWidget(self.warpEditor)
        self.personEditor = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.personEditor.sizePolicy().hasHeightForWidth())
        self.personEditor.setSizePolicy(sizePolicy)
        self.personEditor.setObjectName("personEditor")
        self.formLayout = QtWidgets.QFormLayout(self.personEditor)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_16 = QtWidgets.QLabel(self.personEditor)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.person_num = QtWidgets.QLineEdit(self.personEditor)
        self.person_num.setInputMask("")
        self.person_num.setObjectName("person_num")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.person_num)
        self.label_17 = QtWidgets.QLabel(self.personEditor)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.personEditor)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self._3 = QtWidgets.QHBoxLayout()
        self._3.setObjectName("_3")
        self.p_unknown1 = QtWidgets.QLineEdit(self.personEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_unknown1.sizePolicy().hasHeightForWidth())
        self.p_unknown1.setSizePolicy(sizePolicy)
        self.p_unknown1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.p_unknown1.setObjectName("p_unknown1")
        self._3.addWidget(self.p_unknown1)
        self.p_unknown2 = QtWidgets.QLineEdit(self.personEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_unknown2.sizePolicy().hasHeightForWidth())
        self.p_unknown2.setSizePolicy(sizePolicy)
        self.p_unknown2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.p_unknown2.setObjectName("p_unknown2")
        self._3.addWidget(self.p_unknown2)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self._3)
        self.label_15 = QtWidgets.QLabel(self.personEditor)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self._2 = QtWidgets.QHBoxLayout()
        self._2.setObjectName("_2")
        self.p_x = QtWidgets.QLineEdit(self.personEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_x.sizePolicy().hasHeightForWidth())
        self.p_x.setSizePolicy(sizePolicy)
        self.p_x.setMaximumSize(QtCore.QSize(40, 16777215))
        self.p_x.setObjectName("p_x")
        self._2.addWidget(self.p_x)
        self.p_y = QtWidgets.QLineEdit(self.personEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_y.sizePolicy().hasHeightForWidth())
        self.p_y.setSizePolicy(sizePolicy)
        self.p_y.setMaximumSize(QtCore.QSize(40, 16777215))
        self.p_y.setObjectName("p_y")
        self._2.addWidget(self.p_y)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self._2)
        self.label_19 = QtWidgets.QLabel(self.personEditor)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.p_unknown3 = QtWidgets.QLineEdit(self.personEditor)
        self.p_unknown3.setObjectName("p_unknown3")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.p_unknown3)
        self.label_20 = QtWidgets.QLabel(self.personEditor)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.p_mov_type = QtWidgets.QComboBox(self.personEditor)
        self.p_mov_type.setObjectName("p_mov_type")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.p_mov_type.addItem("")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.p_mov_type)
        self.label_21 = QtWidgets.QLabel(self.personEditor)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.p_mov = QtWidgets.QLineEdit(self.personEditor)
        self.p_mov.setObjectName("p_mov")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.p_mov)
        self.label_22 = QtWidgets.QLabel(self.personEditor)
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.p_unknown4 = QtWidgets.QLineEdit(self.personEditor)
        self.p_unknown4.setObjectName("p_unknown4")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.p_unknown4)
        self.label_23 = QtWidgets.QLabel(self.personEditor)
        self.label_23.setObjectName("label_23")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.label_24 = QtWidgets.QLabel(self.personEditor)
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.label_25 = QtWidgets.QLabel(self.personEditor)
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.label_26 = QtWidgets.QLabel(self.personEditor)
        self.label_26.setObjectName("label_26")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.label_27 = QtWidgets.QLabel(self.personEditor)
        self.label_27.setObjectName("label_27")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.p_flag = QtWidgets.QLineEdit(self.personEditor)
        self.p_flag.setObjectName("p_flag")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.p_flag)
        self.label_28 = QtWidgets.QLabel(self.personEditor)
        self.label_28.setObjectName("label_28")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self._6 = QtWidgets.QHBoxLayout()
        self._6.setObjectName("_6")
        self.p_unknown6 = QtWidgets.QLineEdit(self.personEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_unknown6.sizePolicy().hasHeightForWidth())
        self.p_unknown6.setSizePolicy(sizePolicy)
        self.p_unknown6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.p_unknown6.setObjectName("p_unknown6")
        self._6.addWidget(self.p_unknown6)
        self.p_unknown7 = QtWidgets.QLineEdit(self.personEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_unknown7.sizePolicy().hasHeightForWidth())
        self.p_unknown7.setSizePolicy(sizePolicy)
        self.p_unknown7.setMaximumSize(QtCore.QSize(40, 16777215))
        self.p_unknown7.setObjectName("p_unknown7")
        self._6.addWidget(self.p_unknown7)
        self.formLayout.setLayout(17, QtWidgets.QFormLayout.FieldRole, self._6)
        self.p_script_offset = QtWidgets.QLineEdit(self.personEditor)
        self.p_script_offset.setObjectName("p_script_offset")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.p_script_offset)
        self.p_view_radius = QtWidgets.QLineEdit(self.personEditor)
        self.p_view_radius.setObjectName("p_view_radius")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.p_view_radius)
        self.p_unknown5 = QtWidgets.QLineEdit(self.personEditor)
        self.p_unknown5.setObjectName("p_unknown5")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.p_unknown5)
        self.p_edit_script = QtWidgets.QPushButton(self.personEditor)
        self.p_edit_script.setObjectName("p_edit_script")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.p_edit_script)
        self.spriteImg = QtWidgets.QGraphicsView(self.personEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spriteImg.sizePolicy().hasHeightForWidth())
        self.spriteImg.setSizePolicy(sizePolicy)
        self.spriteImg.setMinimumSize(QtCore.QSize(16, 32))
        self.spriteImg.setMaximumSize(QtCore.QSize(16, 32))
        self.spriteImg.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.spriteImg.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.spriteImg.setObjectName("spriteImg")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spriteImg)
        self.label_9 = QtWidgets.QLabel(self.personEditor)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.sprite_num = QtWidgets.QSpinBox(self.personEditor)
        self.sprite_num.setPrefix("")
        self.sprite_num.setObjectName("sprite_num")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sprite_num)
        self.is_a_trainer = QtWidgets.QLineEdit(self.personEditor)
        self.is_a_trainer.setObjectName("is_a_trainer")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.is_a_trainer)
        self.eventsStackedWidget.addWidget(self.personEditor)
        self.triggerEditor = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.triggerEditor.sizePolicy().hasHeightForWidth())
        self.triggerEditor.setSizePolicy(sizePolicy)
        self.triggerEditor.setObjectName("triggerEditor")
        self.formLayout_3 = QtWidgets.QFormLayout(self.triggerEditor)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_3 = QtWidgets.QLabel(self.triggerEditor)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self._4 = QtWidgets.QHBoxLayout()
        self._4.setObjectName("_4")
        self.t_x = QtWidgets.QLineEdit(self.triggerEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_x.sizePolicy().hasHeightForWidth())
        self.t_x.setSizePolicy(sizePolicy)
        self.t_x.setMaximumSize(QtCore.QSize(40, 16777215))
        self.t_x.setObjectName("t_x")
        self._4.addWidget(self.t_x)
        self.t_y = QtWidgets.QLineEdit(self.triggerEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_y.sizePolicy().hasHeightForWidth())
        self.t_y.setSizePolicy(sizePolicy)
        self.t_y.setMaximumSize(QtCore.QSize(40, 16777215))
        self.t_y.setObjectName("t_y")
        self._4.addWidget(self.t_y)
        self.formLayout_3.setLayout(1, QtWidgets.QFormLayout.FieldRole, self._4)
        self.label_2 = QtWidgets.QLabel(self.triggerEditor)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.t_unknown1 = QtWidgets.QLineEdit(self.triggerEditor)
        self.t_unknown1.setObjectName("t_unknown1")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.t_unknown1)
        self.label_6 = QtWidgets.QLabel(self.triggerEditor)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.t_var_num = QtWidgets.QLineEdit(self.triggerEditor)
        self.t_var_num.setObjectName("t_var_num")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.t_var_num)
        self.label_8 = QtWidgets.QLabel(self.triggerEditor)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_29 = QtWidgets.QLabel(self.triggerEditor)
        self.label_29.setObjectName("label_29")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.t_var_val = QtWidgets.QLineEdit(self.triggerEditor)
        self.t_var_val.setObjectName("t_var_val")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.t_var_val)
        self._5 = QtWidgets.QHBoxLayout()
        self._5.setObjectName("_5")
        self.t_unknown2 = QtWidgets.QLineEdit(self.triggerEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_unknown2.sizePolicy().hasHeightForWidth())
        self.t_unknown2.setSizePolicy(sizePolicy)
        self.t_unknown2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.t_unknown2.setObjectName("t_unknown2")
        self._5.addWidget(self.t_unknown2)
        self.t_unknown3 = QtWidgets.QLineEdit(self.triggerEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_unknown3.sizePolicy().hasHeightForWidth())
        self.t_unknown3.setSizePolicy(sizePolicy)
        self.t_unknown3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.t_unknown3.setObjectName("t_unknown3")
        self._5.addWidget(self.t_unknown3)
        self.formLayout_3.setLayout(5, QtWidgets.QFormLayout.FieldRole, self._5)
        self.t_script_offset = QtWidgets.QLineEdit(self.triggerEditor)
        self.t_script_offset.setObjectName("t_script_offset")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.t_script_offset)
        self.label_30 = QtWidgets.QLabel(self.triggerEditor)
        self.label_30.setObjectName("label_30")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.t_edit_script = QtWidgets.QPushButton(self.triggerEditor)
        self.t_edit_script.setObjectName("t_edit_script")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.t_edit_script)
        self.eventsStackedWidget.addWidget(self.triggerEditor)
        self.signpostEditor = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signpostEditor.sizePolicy().hasHeightForWidth())
        self.signpostEditor.setSizePolicy(sizePolicy)
        self.signpostEditor.setObjectName("signpostEditor")
        self.formLayout_4 = QtWidgets.QFormLayout(self.signpostEditor)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_50 = QtWidgets.QLabel(self.signpostEditor)
        self.label_50.setObjectName("label_50")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_50)
        self.label_63 = QtWidgets.QLabel(self.signpostEditor)
        self.label_63.setObjectName("label_63")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_63)
        self._7 = QtWidgets.QHBoxLayout()
        self._7.setObjectName("_7")
        self.s_x = QtWidgets.QLineEdit(self.signpostEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s_x.sizePolicy().hasHeightForWidth())
        self.s_x.setSizePolicy(sizePolicy)
        self.s_x.setMaximumSize(QtCore.QSize(40, 16777215))
        self.s_x.setObjectName("s_x")
        self._7.addWidget(self.s_x)
        self.s_y = QtWidgets.QLineEdit(self.signpostEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s_y.sizePolicy().hasHeightForWidth())
        self.s_y.setSizePolicy(sizePolicy)
        self.s_y.setMaximumSize(QtCore.QSize(40, 16777215))
        self.s_y.setObjectName("s_y")
        self._7.addWidget(self.s_y)
        self.formLayout_4.setLayout(1, QtWidgets.QFormLayout.FieldRole, self._7)
        self.label_65 = QtWidgets.QLabel(self.signpostEditor)
        self.label_65.setObjectName("label_65")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_65)
        self.s_talking_level = QtWidgets.QComboBox(self.signpostEditor)
        self.s_talking_level.setObjectName("s_talking_level")
        self.s_talking_level.addItem("")
        self.s_talking_level.addItem("")
        self.s_talking_level.addItem("")
        self.s_talking_level.addItem("")
        self.s_talking_level.addItem("")
        self.s_talking_level.addItem("")
        self.s_talking_level.addItem("")
        self.s_talking_level.addItem("")
        self.s_talking_level.addItem("")
        self.s_talking_level.addItem("")
        self.s_talking_level.addItem("")
        self.s_talking_level.addItem("")
        self.s_talking_level.addItem("")
        self.s_talking_level.addItem("")
        self.s_talking_level.addItem("")
        self.s_talking_level.addItem("")
        self.s_talking_level.addItem("")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.s_talking_level)
        self.signpost_stacked = QtWidgets.QStackedWidget(self.signpostEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signpost_stacked.sizePolicy().hasHeightForWidth())
        self.signpost_stacked.setSizePolicy(sizePolicy)
        self.signpost_stacked.setMinimumSize(QtCore.QSize(0, 0))
        self.signpost_stacked.setObjectName("signpost_stacked")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.formLayout_5 = QtWidgets.QFormLayout(self.page)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.s_script_offset = QtWidgets.QLineEdit(self.page)
        self.s_script_offset.setObjectName("s_script_offset")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.s_script_offset)
        self.label_64 = QtWidgets.QLabel(self.page)
        self.label_64.setObjectName("label_64")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_64)
        self.s_edit_script = QtWidgets.QPushButton(self.page)
        self.s_edit_script.setObjectName("s_edit_script")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.s_edit_script)
        self.signpost_stacked.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.formLayout_6 = QtWidgets.QFormLayout(self.page_2)
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_31 = QtWidgets.QLabel(self.page_2)
        self.label_31.setObjectName("label_31")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.s_item_id = QtWidgets.QLineEdit(self.page_2)
        self.s_item_id.setObjectName("s_item_id")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.s_item_id)
        self.label_32 = QtWidgets.QLabel(self.page_2)
        self.label_32.setObjectName("label_32")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.s_hidden_id = QtWidgets.QLineEdit(self.page_2)
        self.s_hidden_id.setObjectName("s_hidden_id")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.s_hidden_id)
        self.label_33 = QtWidgets.QLabel(self.page_2)
        self.label_33.setObjectName("label_33")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.s_amount = QtWidgets.QLineEdit(self.page_2)
        self.s_amount.setObjectName("s_amount")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.s_amount)
        self.signpost_stacked.addWidget(self.page_2)
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.signpost_stacked)
        self.label_66 = QtWidgets.QLabel(self.signpostEditor)
        self.label_66.setObjectName("label_66")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_66)
        self.s_type = QtWidgets.QComboBox(self.signpostEditor)
        self.s_type.setObjectName("s_type")
        self.s_type.addItem("")
        self.s_type.addItem("")
        self.s_type.addItem("")
        self.s_type.addItem("")
        self.s_type.addItem("")
        self.s_type.addItem("")
        self.s_type.addItem("")
        self.s_type.addItem("")
        self.s_type.addItem("")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.s_type)
        self.label_34 = QtWidgets.QLabel(self.signpostEditor)
        self.label_34.setObjectName("label_34")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self._9 = QtWidgets.QHBoxLayout()
        self._9.setObjectName("_9")
        self.s_unknown1 = QtWidgets.QLineEdit(self.signpostEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s_unknown1.sizePolicy().hasHeightForWidth())
        self.s_unknown1.setSizePolicy(sizePolicy)
        self.s_unknown1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.s_unknown1.setObjectName("s_unknown1")
        self._9.addWidget(self.s_unknown1)
        self.s_unknown2 = QtWidgets.QLineEdit(self.signpostEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s_unknown2.sizePolicy().hasHeightForWidth())
        self.s_unknown2.setSizePolicy(sizePolicy)
        self.s_unknown2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.s_unknown2.setObjectName("s_unknown2")
        self._9.addWidget(self.s_unknown2)
        self.formLayout_4.setLayout(4, QtWidgets.QFormLayout.FieldRole, self._9)
        self.eventsStackedWidget.addWidget(self.signpostEditor)
        self.verticalLayout_2.addWidget(self.eventsStackedWidget)
        self.rmEventButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.rmEventButton.setObjectName("rmEventButton")
        self.verticalLayout_2.addWidget(self.rmEventButton)
        self.EventsBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EventsBox.sizePolicy().hasHeightForWidth())
        self.EventsBox.setSizePolicy(sizePolicy)
        self.EventsBox.setObjectName("EventsBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.EventsBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.EventsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 2, 1, 1, 1)
        self.addTriggerButton = QtWidgets.QPushButton(self.EventsBox)
        self.addTriggerButton.setEnabled(True)
        self.addTriggerButton.setMaximumSize(QtCore.QSize(27, 16777215))
        self.addTriggerButton.setObjectName("addTriggerButton")
        self.gridLayout_5.addWidget(self.addTriggerButton, 5, 5, 1, 1)
        self.num_of_signposts = QtWidgets.QLabel(self.EventsBox)
        self.num_of_signposts.setObjectName("num_of_signposts")
        self.gridLayout_5.addWidget(self.num_of_signposts, 6, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.EventsBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 5, 1, 1, 1)
        self.num_of_people = QtWidgets.QLabel(self.EventsBox)
        self.num_of_people.setObjectName("num_of_people")
        self.gridLayout_5.addWidget(self.num_of_people, 2, 2, 1, 1)
        self.num_of_triggers = QtWidgets.QLabel(self.EventsBox)
        self.num_of_triggers.setObjectName("num_of_triggers")
        self.gridLayout_5.addWidget(self.num_of_triggers, 5, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.EventsBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 6, 1, 1, 1)
        self.addSignpostButton = QtWidgets.QPushButton(self.EventsBox)
        self.addSignpostButton.setEnabled(True)
        self.addSignpostButton.setMaximumSize(QtCore.QSize(27, 16777215))
        self.addSignpostButton.setObjectName("addSignpostButton")
        self.gridLayout_5.addWidget(self.addSignpostButton, 6, 5, 1, 1)
        self.addPersonButton = QtWidgets.QPushButton(self.EventsBox)
        self.addPersonButton.setEnabled(True)
        self.addPersonButton.setMaximumSize(QtCore.QSize(27, 16777215))
        self.addPersonButton.setObjectName("addPersonButton")
        self.gridLayout_5.addWidget(self.addPersonButton, 2, 5, 1, 1)
        self.remPersonButton = QtWidgets.QPushButton(self.EventsBox)
        self.remPersonButton.setEnabled(True)
        self.remPersonButton.setMaximumSize(QtCore.QSize(27, 16777215))
        self.remPersonButton.setObjectName("remPersonButton")
        self.gridLayout_5.addWidget(self.remPersonButton, 2, 4, 1, 1)
        self.remTriggerButton = QtWidgets.QPushButton(self.EventsBox)
        self.remTriggerButton.setEnabled(True)
        self.remTriggerButton.setMaximumSize(QtCore.QSize(27, 16777215))
        self.remTriggerButton.setObjectName("remTriggerButton")
        self.gridLayout_5.addWidget(self.remTriggerButton, 5, 4, 1, 1)
        self.remSignpostButton = QtWidgets.QPushButton(self.EventsBox)
        self.remSignpostButton.setEnabled(True)
        self.remSignpostButton.setMaximumSize(QtCore.QSize(27, 16777215))
        self.remSignpostButton.setObjectName("remSignpostButton")
        self.gridLayout_5.addWidget(self.remSignpostButton, 6, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.EventsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 3, 1, 1, 1)
        self.num_of_warps = QtWidgets.QLabel(self.EventsBox)
        self.num_of_warps.setObjectName("num_of_warps")
        self.gridLayout_5.addWidget(self.num_of_warps, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 2, 3, 1, 1)
        self.remWarpButton = QtWidgets.QPushButton(self.EventsBox)
        self.remWarpButton.setEnabled(True)
        self.remWarpButton.setMaximumSize(QtCore.QSize(27, 16777215))
        self.remWarpButton.setObjectName("remWarpButton")
        self.gridLayout_5.addWidget(self.remWarpButton, 3, 4, 1, 1)
        self.addWarpButton = QtWidgets.QPushButton(self.EventsBox)
        self.addWarpButton.setEnabled(True)
        self.addWarpButton.setMaximumSize(QtCore.QSize(27, 16777215))
        self.addWarpButton.setObjectName("addWarpButton")
        self.gridLayout_5.addWidget(self.addWarpButton, 3, 5, 1, 1)
        self.verticalLayout_2.addWidget(self.EventsBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 1, 1, 1)
        self.tabWidget.addTab(self.eventsTab, "")
        self.HeaderTab = QtWidgets.QWidget()
        self.HeaderTab.setEnabled(True)
        self.HeaderTab.setObjectName("HeaderTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.HeaderTab)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.HeaderTab)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 877, 731))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.m_data_ptr = QtWidgets.QLineEdit(self.groupBox)
        self.m_data_ptr.setObjectName("m_data_ptr")
        self.gridLayout_12.addWidget(self.m_data_ptr, 0, 1, 1, 1)
        self.e_data_ptr = QtWidgets.QLineEdit(self.groupBox)
        self.e_data_ptr.setObjectName("e_data_ptr")
        self.gridLayout_12.addWidget(self.e_data_ptr, 2, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox)
        self.label_37.setObjectName("label_37")
        self.gridLayout_12.addWidget(self.label_37, 3, 0, 1, 1)
        self.ls_ptr = QtWidgets.QLineEdit(self.groupBox)
        self.ls_ptr.setObjectName("ls_ptr")
        self.gridLayout_12.addWidget(self.ls_ptr, 3, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox)
        self.label_35.setObjectName("label_35")
        self.gridLayout_12.addWidget(self.label_35, 6, 0, 1, 1)
        self.map_type = QtWidgets.QLineEdit(self.groupBox)
        self.map_type.setObjectName("map_type")
        self.gridLayout_12.addWidget(self.map_type, 10, 1, 1, 1)
        self.label_index = QtWidgets.QLineEdit(self.groupBox)
        self.label_index.setObjectName("label_index")
        self.gridLayout_12.addWidget(self.label_index, 6, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox)
        self.label_40.setObjectName("label_40")
        self.gridLayout_12.addWidget(self.label_40, 12, 0, 1, 1)
        self.m_ptr_index = QtWidgets.QLineEdit(self.groupBox)
        self.m_ptr_index.setObjectName("m_ptr_index")
        self.gridLayout_12.addWidget(self.m_ptr_index, 1, 1, 1, 1)
        self.song_index = QtWidgets.QLineEdit(self.groupBox)
        self.song_index.setObjectName("song_index")
        self.gridLayout_12.addWidget(self.song_index, 5, 1, 1, 1)
        self.con_data_ptr = QtWidgets.QLineEdit(self.groupBox)
        self.con_data_ptr.setObjectName("con_data_ptr")
        self.gridLayout_12.addWidget(self.con_data_ptr, 4, 1, 1, 1)
        self.label_103 = QtWidgets.QLabel(self.groupBox)
        self.label_103.setObjectName("label_103")
        self.gridLayout_12.addWidget(self.label_103, 4, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox)
        self.label_42.setObjectName("label_42")
        self.gridLayout_12.addWidget(self.label_42, 7, 0, 1, 1)
        self.label_105 = QtWidgets.QLabel(self.groupBox)
        self.label_105.setObjectName("label_105")
        self.gridLayout_12.addWidget(self.label_105, 1, 0, 1, 1)
        self.weather_type = QtWidgets.QLineEdit(self.groupBox)
        self.weather_type.setObjectName("weather_type")
        self.gridLayout_12.addWidget(self.weather_type, 12, 1, 1, 1)
        self.label_95 = QtWidgets.QLabel(self.groupBox)
        self.label_95.setObjectName("label_95")
        self.gridLayout_12.addWidget(self.label_95, 14, 0, 1, 1)
        self.battle_type = QtWidgets.QLineEdit(self.groupBox)
        self.battle_type.setObjectName("battle_type")
        self.gridLayout_12.addWidget(self.battle_type, 14, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox)
        self.label_38.setObjectName("label_38")
        self.gridLayout_12.addWidget(self.label_38, 2, 0, 1, 1)
        self.label_104 = QtWidgets.QLabel(self.groupBox)
        self.label_104.setObjectName("label_104")
        self.gridLayout_12.addWidget(self.label_104, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem1, 15, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox)
        self.label_36.setObjectName("label_36")
        self.gridLayout_12.addWidget(self.label_36, 0, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox)
        self.label_39.setObjectName("label_39")
        self.gridLayout_12.addWidget(self.label_39, 11, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.groupBox)
        self.label_41.setObjectName("label_41")
        self.gridLayout_12.addWidget(self.label_41, 10, 0, 1, 1)
        self.show_label_byte = QtWidgets.QLineEdit(self.groupBox)
        self.show_label_byte.setObjectName("show_label_byte")
        self.gridLayout_12.addWidget(self.show_label_byte, 7, 1, 1, 1)
        self.is_cave_byte = QtWidgets.QLineEdit(self.groupBox)
        self.is_cave_byte.setObjectName("is_cave_byte")
        self.gridLayout_12.addWidget(self.is_cave_byte, 11, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.t1_ptr = QtWidgets.QLineEdit(self.groupBox_2)
        self.t1_ptr.setObjectName("t1_ptr")
        self.gridLayout_13.addWidget(self.t1_ptr, 4, 2, 1, 1)
        self.label_102 = QtWidgets.QLabel(self.groupBox_2)
        self.label_102.setObjectName("label_102")
        self.gridLayout_13.addWidget(self.label_102, 5, 0, 1, 1)
        self.label_96 = QtWidgets.QLabel(self.groupBox_2)
        self.label_96.setObjectName("label_96")
        self.gridLayout_13.addWidget(self.label_96, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem2, 7, 2, 1, 1)
        self.t2_ptr = QtWidgets.QLineEdit(self.groupBox_2)
        self.t2_ptr.setObjectName("t2_ptr")
        self.gridLayout_13.addWidget(self.t2_ptr, 5, 2, 1, 1)
        self.label_99 = QtWidgets.QLabel(self.groupBox_2)
        self.label_99.setObjectName("label_99")
        self.gridLayout_13.addWidget(self.label_99, 6, 0, 1, 1)
        self.label_100 = QtWidgets.QLabel(self.groupBox_2)
        self.label_100.setObjectName("label_100")
        self.gridLayout_13.addWidget(self.label_100, 3, 0, 1, 1)
        self.border_info_ptr = QtWidgets.QLineEdit(self.groupBox_2)
        self.border_info_ptr.setObjectName("border_info_ptr")
        self.gridLayout_13.addWidget(self.border_info_ptr, 6, 2, 1, 1)
        self.label_101 = QtWidgets.QLabel(self.groupBox_2)
        self.label_101.setObjectName("label_101")
        self.gridLayout_13.addWidget(self.label_101, 4, 0, 1, 1)
        self.tilemap_ptr = QtWidgets.QLineEdit(self.groupBox_2)
        self.tilemap_ptr.setObjectName("tilemap_ptr")
        self.gridLayout_13.addWidget(self.tilemap_ptr, 3, 2, 1, 1)
        self._18 = QtWidgets.QHBoxLayout()
        self._18.setObjectName("_18")
        self.label_97 = QtWidgets.QLabel(self.groupBox_2)
        self.label_97.setObjectName("label_97")
        self._18.addWidget(self.label_97)
        self.map_w = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_w.sizePolicy().hasHeightForWidth())
        self.map_w.setSizePolicy(sizePolicy)
        self.map_w.setMaximumSize(QtCore.QSize(40, 16777215))
        self.map_w.setObjectName("map_w")
        self._18.addWidget(self.map_w)
        self.label_98 = QtWidgets.QLabel(self.groupBox_2)
        self.label_98.setObjectName("label_98")
        self._18.addWidget(self.label_98)
        self.map_h = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_h.sizePolicy().hasHeightForWidth())
        self.map_h.setSizePolicy(sizePolicy)
        self.map_h.setMaximumSize(QtCore.QSize(40, 16777215))
        self.map_h.setObjectName("map_h")
        self._18.addWidget(self.map_h)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._18.addItem(spacerItem3)
        self.gridLayout_13.addLayout(self._18, 0, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.HeaderTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lscriptsLayout = QtWidgets.QVBoxLayout()
        self.lscriptsLayout.setObjectName("lscriptsLayout")
        self.verticalLayout_3.addLayout(self.lscriptsLayout)
        self.addLevelScriptButton = QtWidgets.QPushButton(self.tab)
        self.addLevelScriptButton.setEnabled(False)
        self.addLevelScriptButton.setObjectName("addLevelScriptButton")
        self.verticalLayout_3.addWidget(self.addLevelScriptButton)
        self.gridLayout_9.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.PalTab = QtWidgets.QWidget()
        self.PalTab.setEnabled(True)
        self.PalTab.setObjectName("PalTab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.PalTab)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.PalTab)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_51 = QtWidgets.QLabel(self.groupBox_3)
        self.label_51.setObjectName("label_51")
        self.gridLayout_8.addWidget(self.label_51, 9, 0, 1, 1)
        self.saveBlocksButton = QtWidgets.QPushButton(self.groupBox_3)
        self.saveBlocksButton.setEnabled(False)
        self.saveBlocksButton.setObjectName("saveBlocksButton")
        self.gridLayout_8.addWidget(self.saveBlocksButton, 8, 0, 1, 1)
        self.background1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.background1.setObjectName("background1")
        self.gridLayout_8.addWidget(self.background1, 2, 1, 1, 1)
        self.behaviour1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.behaviour1.setObjectName("behaviour1")
        self.gridLayout_8.addWidget(self.behaviour1, 0, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.groupBox_3)
        self.label_48.setObjectName("label_48")
        self.gridLayout_8.addWidget(self.label_48, 4, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.groupBox_3)
        self.label_49.setObjectName("label_49")
        self.gridLayout_8.addWidget(self.label_49, 5, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox_3)
        self.label_45.setObjectName("label_45")
        self.gridLayout_8.addWidget(self.label_45, 2, 0, 1, 1)
        self.xFlipBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.xFlipBox.setText("")
        self.xFlipBox.setObjectName("xFlipBox")
        self.gridLayout_8.addWidget(self.xFlipBox, 4, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.groupBox_3)
        self.label_44.setObjectName("label_44")
        self.gridLayout_8.addWidget(self.label_44, 1, 0, 1, 1)
        self.behaviour2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.behaviour2.setObjectName("behaviour2")
        self.gridLayout_8.addWidget(self.behaviour2, 1, 1, 1, 1)
        self.background2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.background2.setObjectName("background2")
        self.gridLayout_8.addWidget(self.background2, 3, 1, 1, 1)
        self.yFlipBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.yFlipBox.setText("")
        self.yFlipBox.setObjectName("yFlipBox")
        self.gridLayout_8.addWidget(self.yFlipBox, 5, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.groupBox_3)
        self.label_47.setObjectName("label_47")
        self.gridLayout_8.addWidget(self.label_47, 3, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.groupBox_3)
        self.label_46.setObjectName("label_46")
        self.gridLayout_8.addWidget(self.label_46, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tilePreview = QtWidgets.QGraphicsView(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tilePreview.sizePolicy().hasHeightForWidth())
        self.tilePreview.setSizePolicy(sizePolicy)
        self.tilePreview.setMinimumSize(QtCore.QSize(16, 16))
        self.tilePreview.setMaximumSize(QtCore.QSize(32, 32))
        self.tilePreview.setObjectName("tilePreview")
        self.horizontalLayout_5.addWidget(self.tilePreview)
        self.gridLayout_8.addLayout(self.horizontalLayout_5, 7, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.layer1 = QtWidgets.QGraphicsView(self.groupBox_3)
        self.layer1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layer1.sizePolicy().hasHeightForWidth())
        self.layer1.setSizePolicy(sizePolicy)
        self.layer1.setMaximumSize(QtCore.QSize(64, 64))
        self.layer1.setObjectName("layer1")
        self.horizontalLayout_4.addWidget(self.layer1)
        self.layer2 = QtWidgets.QGraphicsView(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layer2.sizePolicy().hasHeightForWidth())
        self.layer2.setSizePolicy(sizePolicy)
        self.layer2.setMaximumSize(QtCore.QSize(64, 64))
        self.layer2.setObjectName("layer2")
        self.horizontalLayout_4.addWidget(self.layer2)
        self.gridLayout_8.addLayout(self.horizontalLayout_4, 7, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem4, 11, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.groupBox_3)
        self.label_52.setObjectName("label_52")
        self.gridLayout_8.addWidget(self.label_52, 10, 0, 1, 1)
        self.t1_img_ptr = QtWidgets.QLineEdit(self.groupBox_3)
        self.t1_img_ptr.setReadOnly(True)
        self.t1_img_ptr.setObjectName("t1_img_ptr")
        self.gridLayout_8.addWidget(self.t1_img_ptr, 9, 1, 1, 1)
        self.t2_img_ptr = QtWidgets.QLineEdit(self.groupBox_3)
        self.t2_img_ptr.setReadOnly(True)
        self.t2_img_ptr.setObjectName("t2_img_ptr")
        self.gridLayout_8.addWidget(self.t2_img_ptr, 10, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_8)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_43 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout.addWidget(self.label_43)
        self.paletteSelectorCombo = QtWidgets.QComboBox(self.groupBox_4)
        self.paletteSelectorCombo.setEnabled(True)
        self.paletteSelectorCombo.setObjectName("paletteSelectorCombo")
        self.paletteSelectorCombo.addItem("")
        self.paletteSelectorCombo.addItem("")
        self.paletteSelectorCombo.addItem("")
        self.paletteSelectorCombo.addItem("")
        self.paletteSelectorCombo.addItem("")
        self.paletteSelectorCombo.addItem("")
        self.paletteSelectorCombo.addItem("")
        self.paletteSelectorCombo.addItem("")
        self.paletteSelectorCombo.addItem("")
        self.paletteSelectorCombo.addItem("")
        self.paletteSelectorCombo.addItem("")
        self.paletteSelectorCombo.addItem("")
        self.paletteSelectorCombo.addItem("")
        self.horizontalLayout.addWidget(self.paletteSelectorCombo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tileset = QtWidgets.QGraphicsView(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tileset.sizePolicy().hasHeightForWidth())
        self.tileset.setSizePolicy(sizePolicy)
        self.tileset.setMinimumSize(QtCore.QSize(160, 0))
        self.tileset.setMaximumSize(QtCore.QSize(288, 16777215))
        self.tileset.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tileset.setObjectName("tileset")
        self.verticalLayout.addWidget(self.tileset)
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.gridLayout_7.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.edPalette = QtWidgets.QGraphicsView(self.PalTab)
        self.edPalette.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edPalette.sizePolicy().hasHeightForWidth())
        self.edPalette.setSizePolicy(sizePolicy)
        self.edPalette.setMinimumSize(QtCore.QSize(160, 0))
        self.edPalette.setMaximumSize(QtCore.QSize(200, 16777215))
        self.edPalette.setObjectName("edPalette")
        self.gridLayout_7.addWidget(self.edPalette, 0, 0, 1, 1)
        self.tabWidget.addTab(self.PalTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1109, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_ROM = QtWidgets.QAction(MainWindow)
        self.actionLoad_ROM.setObjectName("actionLoad_ROM")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionChoose_script_editor = QtWidgets.QAction(MainWindow)
        self.actionChoose_script_editor.setObjectName("actionChoose_script_editor")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionAdd_new_banks = QtWidgets.QAction(MainWindow)
        self.actionAdd_new_banks.setObjectName("actionAdd_new_banks")
        self.actionExport_Map = QtWidgets.QAction(MainWindow)
        self.actionExport_Map.setObjectName("actionExport_Map")
        self.actionImport_Map = QtWidgets.QAction(MainWindow)
        self.actionImport_Map.setObjectName("actionImport_Map")
        self.menuFile.addAction(self.actionLoad_ROM)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionImport_Map)
        self.menuFile.addAction(self.actionExport_Map)
        self.menuEdit.addAction(self.actionChoose_script_editor)
        self.menuTools.addAction(self.actionAdd_new_banks)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.eventsStackedWidget.setCurrentIndex(0)
        self.signpost_stacked.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.treeView, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.eventSelectorCombo)
        MainWindow.setTabOrder(self.eventSelectorCombo, self.eventSpinBox)
        MainWindow.setTabOrder(self.eventSpinBox, self.w_x)
        MainWindow.setTabOrder(self.w_x, self.w_y)
        MainWindow.setTabOrder(self.w_y, self.w_unknown1)
        MainWindow.setTabOrder(self.w_unknown1, self.w_bank_n)
        MainWindow.setTabOrder(self.w_bank_n, self.w_map_n)
        MainWindow.setTabOrder(self.w_map_n, self.w_warp_n)
        MainWindow.setTabOrder(self.w_warp_n, self.warpGoToMapButton)
        MainWindow.setTabOrder(self.warpGoToMapButton, self.openInEmulatorButton)
        MainWindow.setTabOrder(self.openInEmulatorButton, self.spriteImg)
        MainWindow.setTabOrder(self.spriteImg, self.person_num)
        MainWindow.setTabOrder(self.person_num, self.sprite_num)
        MainWindow.setTabOrder(self.sprite_num, self.p_unknown1)
        MainWindow.setTabOrder(self.p_unknown1, self.p_unknown2)
        MainWindow.setTabOrder(self.p_unknown2, self.p_x)
        MainWindow.setTabOrder(self.p_x, self.p_y)
        MainWindow.setTabOrder(self.p_y, self.p_unknown3)
        MainWindow.setTabOrder(self.p_unknown3, self.p_mov_type)
        MainWindow.setTabOrder(self.p_mov_type, self.p_mov)
        MainWindow.setTabOrder(self.p_mov, self.p_unknown4)
        MainWindow.setTabOrder(self.p_unknown4, self.is_a_trainer)
        MainWindow.setTabOrder(self.is_a_trainer, self.p_unknown5)
        MainWindow.setTabOrder(self.p_unknown5, self.p_view_radius)
        MainWindow.setTabOrder(self.p_view_radius, self.p_script_offset)
        MainWindow.setTabOrder(self.p_script_offset, self.p_edit_script)
        MainWindow.setTabOrder(self.p_edit_script, self.p_flag)
        MainWindow.setTabOrder(self.p_flag, self.p_unknown6)
        MainWindow.setTabOrder(self.p_unknown6, self.p_unknown7)
        MainWindow.setTabOrder(self.p_unknown7, self.rmEventButton)
        MainWindow.setTabOrder(self.rmEventButton, self.remPersonButton)
        MainWindow.setTabOrder(self.remPersonButton, self.addPersonButton)
        MainWindow.setTabOrder(self.addPersonButton, self.remWarpButton)
        MainWindow.setTabOrder(self.remWarpButton, self.addWarpButton)
        MainWindow.setTabOrder(self.addWarpButton, self.remTriggerButton)
        MainWindow.setTabOrder(self.remTriggerButton, self.addTriggerButton)
        MainWindow.setTabOrder(self.addTriggerButton, self.remSignpostButton)
        MainWindow.setTabOrder(self.remSignpostButton, self.addSignpostButton)
        MainWindow.setTabOrder(self.addSignpostButton, self.t_x)
        MainWindow.setTabOrder(self.t_x, self.t_y)
        MainWindow.setTabOrder(self.t_y, self.t_unknown1)
        MainWindow.setTabOrder(self.t_unknown1, self.t_var_num)
        MainWindow.setTabOrder(self.t_var_num, self.t_var_val)
        MainWindow.setTabOrder(self.t_var_val, self.t_unknown2)
        MainWindow.setTabOrder(self.t_unknown2, self.t_unknown3)
        MainWindow.setTabOrder(self.t_unknown3, self.t_script_offset)
        MainWindow.setTabOrder(self.t_script_offset, self.t_edit_script)
        MainWindow.setTabOrder(self.t_edit_script, self.s_x)
        MainWindow.setTabOrder(self.s_x, self.s_y)
        MainWindow.setTabOrder(self.s_y, self.s_talking_level)
        MainWindow.setTabOrder(self.s_talking_level, self.s_type)
        MainWindow.setTabOrder(self.s_type, self.s_unknown1)
        MainWindow.setTabOrder(self.s_unknown1, self.s_unknown2)
        MainWindow.setTabOrder(self.s_unknown2, self.s_script_offset)
        MainWindow.setTabOrder(self.s_script_offset, self.s_edit_script)
        MainWindow.setTabOrder(self.s_edit_script, self.s_item_id)
        MainWindow.setTabOrder(self.s_item_id, self.s_hidden_id)
        MainWindow.setTabOrder(self.s_hidden_id, self.s_amount)
        MainWindow.setTabOrder(self.s_amount, self.m_data_ptr)
        MainWindow.setTabOrder(self.m_data_ptr, self.m_ptr_index)
        MainWindow.setTabOrder(self.m_ptr_index, self.e_data_ptr)
        MainWindow.setTabOrder(self.e_data_ptr, self.ls_ptr)
        MainWindow.setTabOrder(self.ls_ptr, self.con_data_ptr)
        MainWindow.setTabOrder(self.con_data_ptr, self.song_index)
        MainWindow.setTabOrder(self.song_index, self.label_index)
        MainWindow.setTabOrder(self.label_index, self.map_type)
        MainWindow.setTabOrder(self.map_type, self.weather_type)
        MainWindow.setTabOrder(self.weather_type, self.battle_type)
        MainWindow.setTabOrder(self.battle_type, self.map_w)
        MainWindow.setTabOrder(self.map_w, self.map_h)
        MainWindow.setTabOrder(self.map_h, self.tilemap_ptr)
        MainWindow.setTabOrder(self.tilemap_ptr, self.t1_ptr)
        MainWindow.setTabOrder(self.t1_ptr, self.t2_ptr)
        MainWindow.setTabOrder(self.t2_ptr, self.border_info_ptr)
        MainWindow.setTabOrder(self.border_info_ptr, self.addLevelScriptButton)
        MainWindow.setTabOrder(self.addLevelScriptButton, self.behaviour1)
        MainWindow.setTabOrder(self.behaviour1, self.behaviour2)
        MainWindow.setTabOrder(self.behaviour2, self.background1)
        MainWindow.setTabOrder(self.background1, self.background2)
        MainWindow.setTabOrder(self.background2, self.xFlipBox)
        MainWindow.setTabOrder(self.xFlipBox, self.yFlipBox)
        MainWindow.setTabOrder(self.yFlipBox, self.paletteSelectorCombo)
        MainWindow.setTabOrder(self.paletteSelectorCombo, self.map)
        MainWindow.setTabOrder(self.map, self.MovPermissionsPalette)
        MainWindow.setTabOrder(self.MovPermissionsPalette, self.scrollArea_2)
        MainWindow.setTabOrder(self.scrollArea_2, self.movPermissionsMap)
        MainWindow.setTabOrder(self.movPermissionsMap, self.eventMap)
        MainWindow.setTabOrder(self.eventMap, self.layer1)
        MainWindow.setTabOrder(self.layer1, self.layer2)
        MainWindow.setTabOrder(self.layer2, self.palette)
        MainWindow.setTabOrder(self.palette, self.tileset)
        MainWindow.setTabOrder(self.tileset, self.edPalette)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Blue Spider"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mapTab), _translate("MainWindow", "Map"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.movPermissionsTab), _translate("MainWindow", "Movement Permissions"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Select Event"))
        self.eventSelectorCombo.setItemText(0, _translate("MainWindow", "People"))
        self.eventSelectorCombo.setItemText(1, _translate("MainWindow", "Warps"))
        self.eventSelectorCombo.setItemText(2, _translate("MainWindow", "Triggers"))
        self.eventSelectorCombo.setItemText(3, _translate("MainWindow", "Signposts"))
        self.label_10.setText(_translate("MainWindow", "X/Y"))
        self.label_11.setText(_translate("MainWindow", "Unknown"))
        self.label_12.setText(_translate("MainWindow", "Bank num."))
        self.label_13.setText(_translate("MainWindow", "Map num."))
        self.label_14.setText(_translate("MainWindow", "Warp num."))
        self.warpGoToMapButton.setText(_translate("MainWindow", "Go to map"))
        self.openInEmulatorButton.setText(_translate("MainWindow", "Open in emulator"))
        self.label_16.setText(_translate("MainWindow", "Person num."))
        self.label_17.setText(_translate("MainWindow", "Sprite num. (dec)"))
        self.label_18.setText(_translate("MainWindow", "Unknown"))
        self.label_15.setText(_translate("MainWindow", "X/Y"))
        self.label_19.setText(_translate("MainWindow", "Unknown"))
        self.label_20.setText(_translate("MainWindow", "Mov. type"))
        self.p_mov_type.setItemText(0, _translate("MainWindow", "No movement"))
        self.p_mov_type.setItemText(1, _translate("MainWindow", "Look around"))
        self.p_mov_type.setItemText(2, _translate("MainWindow", "Walk around"))
        self.p_mov_type.setItemText(3, _translate("MainWindow", "Walk up and down"))
        self.p_mov_type.setItemText(4, _translate("MainWindow", "Walk up and down"))
        self.p_mov_type.setItemText(5, _translate("MainWindow", "Walk left and right"))
        self.p_mov_type.setItemText(6, _translate("MainWindow", "Walk left and right"))
        self.p_mov_type.setItemText(7, _translate("MainWindow", "Look up"))
        self.p_mov_type.setItemText(8, _translate("MainWindow", "Look down"))
        self.p_mov_type.setItemText(9, _translate("MainWindow", "Look left"))
        self.p_mov_type.setItemText(10, _translate("MainWindow", "Look right"))
        self.p_mov_type.setItemText(11, _translate("MainWindow", "Do NOT use"))
        self.p_mov_type.setItemText(12, _translate("MainWindow", "Hidden"))
        self.p_mov_type.setItemText(13, _translate("MainWindow", "Look up and down"))
        self.p_mov_type.setItemText(14, _translate("MainWindow", "Look left and right"))
        self.p_mov_type.setItemText(15, _translate("MainWindow", "Look up and left"))
        self.p_mov_type.setItemText(16, _translate("MainWindow", "Look up and rigth"))
        self.p_mov_type.setItemText(17, _translate("MainWindow", "Look down and left"))
        self.p_mov_type.setItemText(18, _translate("MainWindow", "Look down and right"))
        self.p_mov_type.setItemText(19, _translate("MainWindow", "Look up, down and left"))
        self.p_mov_type.setItemText(20, _translate("MainWindow", "Look up, down and right"))
        self.p_mov_type.setItemText(21, _translate("MainWindow", "Look up, left and right"))
        self.p_mov_type.setItemText(22, _translate("MainWindow", "Look down, left and right"))
        self.p_mov_type.setItemText(23, _translate("MainWindow", "Look around counterclockwise"))
        self.p_mov_type.setItemText(24, _translate("MainWindow", "Look around clockwise"))
        self.p_mov_type.setItemText(25, _translate("MainWindow", "Run up and down"))
        self.p_mov_type.setItemText(26, _translate("MainWindow", "Run up and down"))
        self.p_mov_type.setItemText(27, _translate("MainWindow", "Run left and right"))
        self.p_mov_type.setItemText(28, _translate("MainWindow", "Run left and right"))
        self.p_mov_type.setItemText(29, _translate("MainWindow", "Run up, right, left and down"))
        self.p_mov_type.setItemText(30, _translate("MainWindow", "Run right, left, down and up"))
        self.p_mov_type.setItemText(31, _translate("MainWindow", "Run down, up, right and left"))
        self.p_mov_type.setItemText(32, _translate("MainWindow", "Run left, down, up and right"))
        self.p_mov_type.setItemText(33, _translate("MainWindow", "Run up, left, right and down"))
        self.p_mov_type.setItemText(34, _translate("MainWindow", "Run left, right down and up"))
        self.p_mov_type.setItemText(35, _translate("MainWindow", "Run down, up, left and right"))
        self.p_mov_type.setItemText(36, _translate("MainWindow", "Run right, down, up and left"))
        self.p_mov_type.setItemText(37, _translate("MainWindow", "Run left, up, down and right"))
        self.p_mov_type.setItemText(38, _translate("MainWindow", "26"))
        self.p_mov_type.setItemText(39, _translate("MainWindow", "27"))
        self.p_mov_type.setItemText(40, _translate("MainWindow", "28"))
        self.p_mov_type.setItemText(41, _translate("MainWindow", "29"))
        self.p_mov_type.setItemText(42, _translate("MainWindow", "2A"))
        self.p_mov_type.setItemText(43, _translate("MainWindow", "2B"))
        self.p_mov_type.setItemText(44, _translate("MainWindow", "2C"))
        self.p_mov_type.setItemText(45, _translate("MainWindow", "2D"))
        self.p_mov_type.setItemText(46, _translate("MainWindow", "2E"))
        self.p_mov_type.setItemText(47, _translate("MainWindow", "2F"))
        self.p_mov_type.setItemText(48, _translate("MainWindow", "30"))
        self.p_mov_type.setItemText(49, _translate("MainWindow", "31"))
        self.p_mov_type.setItemText(50, _translate("MainWindow", "32"))
        self.p_mov_type.setItemText(51, _translate("MainWindow", "33"))
        self.p_mov_type.setItemText(52, _translate("MainWindow", "34"))
        self.p_mov_type.setItemText(53, _translate("MainWindow", "35"))
        self.p_mov_type.setItemText(54, _translate("MainWindow", "36"))
        self.p_mov_type.setItemText(55, _translate("MainWindow", "37"))
        self.p_mov_type.setItemText(56, _translate("MainWindow", "38"))
        self.p_mov_type.setItemText(57, _translate("MainWindow", "39"))
        self.p_mov_type.setItemText(58, _translate("MainWindow", "3A"))
        self.p_mov_type.setItemText(59, _translate("MainWindow", "3B"))
        self.p_mov_type.setItemText(60, _translate("MainWindow", "3C"))
        self.p_mov_type.setItemText(61, _translate("MainWindow", "3D"))
        self.p_mov_type.setItemText(62, _translate("MainWindow", "3E"))
        self.p_mov_type.setItemText(63, _translate("MainWindow", "3F"))
        self.p_mov_type.setItemText(64, _translate("MainWindow", "40"))
        self.p_mov_type.setItemText(65, _translate("MainWindow", "41"))
        self.p_mov_type.setItemText(66, _translate("MainWindow", "42"))
        self.p_mov_type.setItemText(67, _translate("MainWindow", "43"))
        self.p_mov_type.setItemText(68, _translate("MainWindow", "44"))
        self.p_mov_type.setItemText(69, _translate("MainWindow", "45"))
        self.p_mov_type.setItemText(70, _translate("MainWindow", "46"))
        self.p_mov_type.setItemText(71, _translate("MainWindow", "47"))
        self.p_mov_type.setItemText(72, _translate("MainWindow", "48"))
        self.p_mov_type.setItemText(73, _translate("MainWindow", "49"))
        self.p_mov_type.setItemText(74, _translate("MainWindow", "4A"))
        self.p_mov_type.setItemText(75, _translate("MainWindow", "4B"))
        self.p_mov_type.setItemText(76, _translate("MainWindow", "4C"))
        self.p_mov_type.setItemText(77, _translate("MainWindow", "4D"))
        self.p_mov_type.setItemText(78, _translate("MainWindow", "4E"))
        self.p_mov_type.setItemText(79, _translate("MainWindow", "4F"))
        self.p_mov_type.setItemText(80, _translate("MainWindow", "50"))
        self.label_21.setText(_translate("MainWindow", "Movement"))
        self.label_22.setText(_translate("MainWindow", "Unknown"))
        self.label_23.setText(_translate("MainWindow", "Is a trainer"))
        self.label_24.setText(_translate("MainWindow", "Unknown"))
        self.label_25.setText(_translate("MainWindow", "View radius"))
        self.label_26.setText(_translate("MainWindow", "Script offset"))
        self.label_27.setText(_translate("MainWindow", "Flag"))
        self.label_28.setText(_translate("MainWindow", "Unknown"))
        self.p_edit_script.setText(_translate("MainWindow", "Edit Script"))
        self.label_9.setText(_translate("MainWindow", "Sprite"))
        self.label_3.setText(_translate("MainWindow", "X/Y"))
        self.label_2.setText(_translate("MainWindow", "Unknown"))
        self.label_6.setText(_translate("MainWindow", "Var Number"))
        self.label_8.setText(_translate("MainWindow", "Var value"))
        self.label_29.setText(_translate("MainWindow", "Unknown"))
        self.label_30.setText(_translate("MainWindow", "Script offset"))
        self.t_edit_script.setText(_translate("MainWindow", "Edit Script"))
        self.label_50.setText(_translate("MainWindow", "Signpost"))
        self.label_63.setText(_translate("MainWindow", "X/Y"))
        self.label_65.setText(_translate("MainWindow", "Talking level"))
        self.s_talking_level.setItemText(0, _translate("MainWindow", "Always"))
        self.s_talking_level.setItemText(1, _translate("MainWindow", "0 Surf"))
        self.s_talking_level.setItemText(2, _translate("MainWindow", "1"))
        self.s_talking_level.setItemText(3, _translate("MainWindow", "2 Normal"))
        self.s_talking_level.setItemText(4, _translate("MainWindow", "3"))
        self.s_talking_level.setItemText(5, _translate("MainWindow", "4"))
        self.s_talking_level.setItemText(6, _translate("MainWindow", "5"))
        self.s_talking_level.setItemText(7, _translate("MainWindow", "6"))
        self.s_talking_level.setItemText(8, _translate("MainWindow", "7"))
        self.s_talking_level.setItemText(9, _translate("MainWindow", "8"))
        self.s_talking_level.setItemText(10, _translate("MainWindow", "9"))
        self.s_talking_level.setItemText(11, _translate("MainWindow", "A"))
        self.s_talking_level.setItemText(12, _translate("MainWindow", "B"))
        self.s_talking_level.setItemText(13, _translate("MainWindow", "C"))
        self.s_talking_level.setItemText(14, _translate("MainWindow", "D"))
        self.s_talking_level.setItemText(15, _translate("MainWindow", "E"))
        self.s_talking_level.setItemText(16, _translate("MainWindow", "F"))
        self.label_64.setText(_translate("MainWindow", "Script Offset"))
        self.s_edit_script.setText(_translate("MainWindow", "Edit Script"))
        self.label_31.setText(_translate("MainWindow", "Item Id"))
        self.label_32.setText(_translate("MainWindow", "Hidden Id"))
        self.label_33.setText(_translate("MainWindow", "Amount"))
        self.label_66.setText(_translate("MainWindow", "Type"))
        self.s_type.setItemText(0, _translate("MainWindow", "Script"))
        self.s_type.setItemText(1, _translate("MainWindow", "Script if player is facing up"))
        self.s_type.setItemText(2, _translate("MainWindow", "Script if player is facing down"))
        self.s_type.setItemText(3, _translate("MainWindow", "Script if player is facing right"))
        self.s_type.setItemText(4, _translate("MainWindow", "Script if player is facing left"))
        self.s_type.setItemText(5, _translate("MainWindow", "Hidden item"))
        self.s_type.setItemText(6, _translate("MainWindow", "Hidden item"))
        self.s_type.setItemText(7, _translate("MainWindow", "Hidden item"))
        self.s_type.setItemText(8, _translate("MainWindow", "Secret base"))
        self.label_34.setText(_translate("MainWindow", "Unknown"))
        self.rmEventButton.setText(_translate("MainWindow", "Delete event"))
        self.EventsBox.setTitle(_translate("MainWindow", "Add events"))
        self.label_4.setText(_translate("MainWindow", "People:"))
        self.addTriggerButton.setText(_translate("MainWindow", "+"))
        self.num_of_signposts.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Triggers:"))
        self.num_of_people.setText(_translate("MainWindow", "0"))
        self.num_of_triggers.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Signposts:"))
        self.addSignpostButton.setText(_translate("MainWindow", "+"))
        self.addPersonButton.setText(_translate("MainWindow", "+"))
        self.remPersonButton.setText(_translate("MainWindow", "-"))
        self.remTriggerButton.setText(_translate("MainWindow", "-"))
        self.remSignpostButton.setText(_translate("MainWindow", "-"))
        self.label.setText(_translate("MainWindow", "Warps: "))
        self.num_of_warps.setText(_translate("MainWindow", "0"))
        self.remWarpButton.setText(_translate("MainWindow", "-"))
        self.addWarpButton.setText(_translate("MainWindow", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.eventsTab), _translate("MainWindow", "Events"))
        self.groupBox.setTitle(_translate("MainWindow", "Map Header"))
        self.label_37.setText(_translate("MainWindow", "Level script Address"))
        self.label_35.setText(_translate("MainWindow", "Label Index"))
        self.label_40.setText(_translate("MainWindow", "Weather Type Number"))
        self.label_103.setText(_translate("MainWindow", "Connection Data Address"))
        self.label_42.setText(_translate("MainWindow", "Show Label on Entering"))
        self.label_105.setText(_translate("MainWindow", "Map Address Index"))
        self.label_95.setText(_translate("MainWindow", "Battle Type"))
        self.label_38.setText(_translate("MainWindow", "Event Data Address"))
        self.label_104.setText(_translate("MainWindow", "Song Index"))
        self.label_36.setText(_translate("MainWindow", "Map Data Address"))
        self.label_39.setText(_translate("MainWindow", "Is a Cave"))
        self.label_41.setText(_translate("MainWindow", "Map Type Number"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Map Data"))
        self.label_102.setText(_translate("MainWindow", "Local Tileset Address"))
        self.label_96.setText(_translate("MainWindow", "Dimensions:"))
        self.label_99.setText(_translate("MainWindow", "Border Info Address"))
        self.label_100.setText(_translate("MainWindow", "Tilemap Address"))
        self.label_101.setText(_translate("MainWindow", "Global Tileset Address"))
        self.label_97.setText(_translate("MainWindow", "Width"))
        self.label_98.setText(_translate("MainWindow", "Height"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.HeaderTab), _translate("MainWindow", "Header"))
        self.addLevelScriptButton.setText(_translate("MainWindow", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Level Scripts"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Properties"))
        self.label_51.setText(_translate("MainWindow", "Tileset 1 image"))
        self.saveBlocksButton.setText(_translate("MainWindow", "Save Blocks"))
        self.label_48.setText(_translate("MainWindow", "Horizontal Flip"))
        self.label_49.setText(_translate("MainWindow", "Vertical Flip"))
        self.label_45.setText(_translate("MainWindow", "Background"))
        self.label_44.setText(_translate("MainWindow", "Behaviour 2"))
        self.label_47.setText(_translate("MainWindow", "Background 2"))
        self.label_46.setText(_translate("MainWindow", "Behaviour"))
        self.label_52.setText(_translate("MainWindow", "Tileset 2 image"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Tileset"))
        self.label_43.setText(_translate("MainWindow", "Palette"))
        self.paletteSelectorCombo.setItemText(0, _translate("MainWindow", "0"))
        self.paletteSelectorCombo.setItemText(1, _translate("MainWindow", "1"))
        self.paletteSelectorCombo.setItemText(2, _translate("MainWindow", "2"))
        self.paletteSelectorCombo.setItemText(3, _translate("MainWindow", "3"))
        self.paletteSelectorCombo.setItemText(4, _translate("MainWindow", "4"))
        self.paletteSelectorCombo.setItemText(5, _translate("MainWindow", "5"))
        self.paletteSelectorCombo.setItemText(6, _translate("MainWindow", "6"))
        self.paletteSelectorCombo.setItemText(7, _translate("MainWindow", "7"))
        self.paletteSelectorCombo.setItemText(8, _translate("MainWindow", "8"))
        self.paletteSelectorCombo.setItemText(9, _translate("MainWindow", "9"))
        self.paletteSelectorCombo.setItemText(10, _translate("MainWindow", "10"))
        self.paletteSelectorCombo.setItemText(11, _translate("MainWindow", "11"))
        self.paletteSelectorCombo.setItemText(12, _translate("MainWindow", "12"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PalTab), _translate("MainWindow", "Tilemap Palette"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuEdit.setTitle(_translate("MainWindow", "E&dit"))
        self.menuTools.setTitle(_translate("MainWindow", "&Tools"))
        self.actionLoad_ROM.setText(_translate("MainWindow", "&Load ROM"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionChoose_script_editor.setText(_translate("MainWindow", "&Select script editor"))
        self.actionSave_As.setText(_translate("MainWindow", "Sa&ve As"))
        self.actionAdd_new_banks.setText(_translate("MainWindow", "&Add new banks"))
        self.actionExport_Map.setText(_translate("MainWindow", "&Export Map"))
        self.actionImport_Map.setText(_translate("MainWindow", "&Import Map"))

